### ISSUE TITLE
dipole moments

### ISSUE THREAD

**Issue by sharcdyn** [nubakery/bagel#103]
Hi,

When trying to calculate dipole moments without being in a singlet state the calculations is not working. This happens with regular CI and also with relativistic CI.

Any idea what is happening? What about dipole moments in perturbation theory? Is there any way to extract the orbitals with the phase in a relativistic CAS so that dipole can be obtained directly with the reduced density matrix?

Thank you,

Jesús

**Comment by shiozaki** [comment]
Can you provide us with an input and expected result?

Every method whose nuclear gradient is implemented should provide correct dipole moment (using relaxed density matrices). They have been debugged using finite electric field. For example, non-relativistic CASPT2 dipole is working; MRCI dipole is not implemented.

Note that you can calculate dipole using finite field. See hf_svp_dfhf_ext.json in the test directly as to how to specify the external electric field.

**Comment by sharcdyn** [comment]
Attached to this mail I send you results for I atom, where it can be seen that asking by dipoles the code unexpectedly fails.
[I-dipoles.zip](https://github.com/nubakery/bagel/files/1192774/I-dipoles.zip)

On the other hand, it is not clear for me how it can be used an external field to calculate transition dipole moments.

Finally, is there any way to calculate dipole transitions in a relativistic calculation?

**Comment by shiozaki** [comment]
Dipole moments are the derivative of the energy with respect to the external electric field (the derivative is taken at zero field). You could use finite-difference formula to approximate the derivative.

There is no transition dipole moment implemented.

I will check the dipole moment in FCI (this was written by someone else, so it will take a bit).

**Comment by shiozaki** [comment]
Dipole code in non-relativistic FCI should work now. I may implement relativistic one in the next few weeks, but since it is not documented in the manual, I will close this issue. Please check back in some time.
