### ISSUE TITLE
Natural Occupation numbers not printed

### ISSUE THREAD

**Issue by sheepforce** [nubakery/bagel#104]
Hi,
when doing a CASSCF calculation the `nattoc` keyword should print natural occupation numbers to the `casscf.log`, according to the manual. But natural occupation numbers are neither printed to the `casscf.log` nor to the molden file.

**Comment by shiozaki** [comment]
They are printed in casscf.log - can you grep "natural occupation numbers"?

The occupation numbers in the last iteration should correspond to the active orbitals. For some reasons it is now in the ascending order, but am changing it now to the descending order.

**Comment by RDReynolds** [comment]
Is it possible you just have a typo in your input file?  The keyword is "natocc", not "nattoc".

**Comment by sheepforce** [comment]
You are right the problem was indeed wrong spelling. Sorry for the inconvenience. 
Is it possible to write the natural orbitals and the natural occupation numbers to the molden file?

**Comment by shiozaki** [comment]
If you print to Molden right after CASSCF, the orbitals that show up in the file should be natural orbitals within the active space. From the design standpoint it;s not easy to pass around the occupation number, but will think about it. Let me close the issue for the time being.
