### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by lucamontana** [nubakery/bagel#105]
Dear Developers, 

I have the following linking error when compiling Bagel :  
-------------------------------------------------------------------------

libtool: link: mpicxx -I../.. -I/home/luca/bag/boost_1_64_0 -DNDEBUG -O3 -mavx -std=c++11 -o .libs/BAGEL main.o  -L/home/luca/bag/boost_1_64_0/stage/lib ./.libs/libbagel.so opt/.libs/libbagel_opt.so multi/zcasscf/.libs/libbagel_zcasscf.so ci/zfci/.libs/libbagel_zfci.so ci/fci/.libs/libbagel_fci.so ci/ras/.libs/libbagel_ras.so scf/.libs/libbagel_scf.so multi/casscf/.libs/libbagel_casscf.so pt2/.libs/libbagel_pt2.so grad/.libs/libbagel_grad.so wfn/.libs/libbagel_wfn.so df/.libs/libbagel_df.so smith/.libs/libbagel_smith.so prop/.libs/libbagel_prop.so asd/.libs/libbagel_asd.so asd/dmrg/.libs/libbagel_asd_dmrg.so asd/orbital/.libs/libbagel_asd_orbital.so asd/dimer/.libs/libbagel_dimer.so asd/multisite/.libs/libbagel_multisite.so ci/ciutil/.libs/libbagel_ciutil.so mat1e/.libs/libbagel_mat1e.so periodic/.libs/libbagel_periodic.so integral/.libs/libbagel_integral.so molecule/.libs/libbagel_molecule.so util/io/.libs/libbagel_io.so util/.libs/libbagel_util.so util/parallel/.libs/libbagel_parallel.so util/math/.libs/libbagel_math.so util/input/.libs/libbagel_input.so -lmkl_scalapack_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -lboost_unit_test_framework -lboost_regex -lboost_serialization -Wl,-rpath -Wl,/usr/local/bagel/lib
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector_impl<double>::element(std::bitset<64ul>, std::bitset<64ul>)'
pt2/.libs/libbagel_pt2.so: undefined reference to `vtable for bagel::ZCASSCF'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::ZHarrison::read_external_rdm1(int, int, std::string const&) const'
asd/.libs/libbagel_asd.so: undefined reference to `vtable for bagel::RASCivector_impl<double>'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::rdm3(int, int) const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::ApplyOperator::operator()(double, bagel::RASBlockVectors const&, bagel::RASBlockVectors&, std::vector<bagel::GammaSQ, std::allocator<bagel::GammaSQ> > const&, std::vector<int, std::allocator<int> > const&) const'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASDeterminants::RASDeterminants(int, int, int, int, int, int, int, bool)'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RASCivecView_<double>::RASCivecView_(std::shared_ptr<bagel::RASDeterminants const>, double*)'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RASCivector<double>::RASCivector(bagel::RASCivecView_<double> const&)'
asd/.libs/libbagel_asd.so: undefined reference to `vtable for bagel::RASCivector<double>'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::FormSigmaRAS::operator()(std::shared_ptr<bagel::Dvector_base<bagel::RASCivector<double> > const>, std::shared_ptr<bagel::MOFile const>, std::vector<int, std::allocator<int> > const&) const'
wfn/.libs/libbagel_wfn.so: undefined reference to `vtable for bagel::ZHarrison'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::spin() const'
prop/.libs/libbagel_prop.so: undefined reference to `bagel::RelDvector<std::complex<double> >::find(int, int) const'
pt2/.libs/libbagel_pt2.so: undefined reference to `bagel::ZCASSCF::ZCASSCF(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>)'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RAS::spin_raise_impl(bagel::RASCivecView_<double>, bagel::RASCivecView_<double>)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::read_external_rdm12_av(std::string const&)'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector_impl<double>::norm() const'
wfn/.libs/libbagel_wfn.so: undefined reference to `typeinfo for bagel::ZHarrison'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZCASSCF::conv_to_ref() const'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::RelDvector<std::complex<double> >::size() const'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::RelDvector<std::complex<double> >::extract_state(std::vector<int, std::allocator<int> >) const'
pt2/.libs/libbagel_pt2.so: undefined reference to `bagel::RelMOFile::compute_full(std::shared_ptr<bagel::ZMatrix const>, std::list<std::shared_ptr<bagel::RelDFHalf>, std::allocator<std::shared_ptr<bagel::RelDFHalf> > >, bool)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::RASCI::RASCI(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::conv_to_ciwfn() const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RASCivecView_<double>::RASCivecView_(std::shared_ptr<bagel::RASDeterminants const>, double const*)'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::ZHarrison::read_external_rdm2(int, int, std::string const&) const'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::RelDvector<std::complex<double> >::clone() const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RASCivector_impl<double>::normalize()'
pt2/.libs/libbagel_pt2.so: undefined reference to `vtable for bagel::ZCASSecond'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::Sparse_IJ::Sparse_IJ(std::shared_ptr<bagel::CIStringSet<bagel::RASString, void> const>, std::shared_ptr<bagel::CIStringSet<bagel::RASString, void> const>)'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::ZHarrison::read_external_rdm3(int, int, std::string const&) const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RAS::DenomTask::compute()'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RAS::spin_lower_impl(bagel::RASCivecView_<double>, bagel::RASCivecView_<double>)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::rdm1(int, int) const'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::spin_lower(std::shared_ptr<bagel::RASDeterminants const>) const'
pt2/.libs/libbagel_pt2.so: undefined reference to `bagel::RelMOFile::compute_half(std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::ZMatrix const>, bool, bool)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::rdm4(int, int) const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::ApplyOperator::operator()(double, bagel::RASCivecView_<double>, bagel::RASCivecView_<double>, std::vector<bagel::GammaSQ, std::allocator<bagel::GammaSQ> > const&, std::vector<int, std::allocator<int> > const&) const'
smith/.libs/libbagel_smith.so: undefined reference to `bagel::ZHarrison::read_external_rdm4(int, int, std::string const&) const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RASCivector_impl<double>::print(double) const'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RASCivecView_<double>::RASCivecView_(bagel::RASCivecView_<double> const&)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZFCI_bare::ZFCI_bare(std::shared_ptr<bagel::CIWfn_<bagel::RelDvector<std::complex<double> >, std::pair<std::shared_ptr<bagel::RelSpace const>, std::shared_ptr<bagel::RelSpace const> > > const>)'
asd/dmrg/.libs/libbagel_asd_dmrg.so: undefined reference to `bagel::RAS::spin_impl(bagel::RASCivecView_<double>, bagel::RASCivecView_<double>)'
wfn/.libs/libbagel_wfn.so: undefined reference to `typeinfo for bagel::ZCASSCF'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::RASCivector(std::shared_ptr<bagel::RASDeterminants const>)'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::ZHarrison(std::shared_ptr<bagel::PTree const>, std::shared_ptr<bagel::Geometry const>, std::shared_ptr<bagel::Reference const>, int, int, std::shared_ptr<bagel::RelCoeff_Block const>, bool, bool)'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::RASCivector(std::shared_ptr<bagel::RASCivector<double> const>)'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::FormSigmaRAS::operator()(std::shared_ptr<bagel::Dvector_base<bagel::RASCivector<double> > const>, std::shared_ptr<bagel::Matrix const>, std::shared_ptr<bagel::Matrix const>, std::vector<int, std::allocator<int> > const&) const'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::compute_rdm12()'
wfn/.libs/libbagel_wfn.so: undefined reference to `bagel::ZHarrison::rdm2(int, int) const'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::spin_raise(std::shared_ptr<bagel::RASDeterminants const>) const'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector<double>::RASCivector(bagel::RASCivector<double> const&)'
asd/.libs/libbagel_asd.so: undefined reference to `bagel::RASCivector_impl<double>::synchronize(int)'
collect2: error: ld returned 1 exit status
Makefile:522: recipe for target 'BAGEL' failed
make[3]: *** [BAGEL] Error 1
make[3]: Leaving directory '/home/luca/bag/bagel/bi/src'
Makefile:573: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/luca/bag/bagel/bi/src'
Makefile:405: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/luca/bag/bagel/bi'
Makefile:336: recipe for target 'all' failed
make: *** [all] Error 2

-------------------------------------------------------------------------------------------------------------------------
I am using this configuration as suggested : 
../configure 'LDFLAGS=-L/home/luca/bag/boost_1_64_0/stage/lib' 'CXXFLAGS=-DNDEBUG -O3 -mavx' '--enable-mkl' '--with-include= -I/home/luca/bag/boost_1_64_0' '--with-mpi=intel'

Best wishes,
LUCA

**Comment by shiozaki** [comment]
This is not a BAGEL problem. My suggestion is to compile again from scratch (do "make distclean" and then compile again). Another is to compile with "--enable-static --disable-shared". I'll close this.
