### ISSUE TITLE
A typo in zcassecond.cc

### ISSUE THREAD

**Issue by DanielWicz** [nubakery/bagel#111]
Hello

I have been trying to compile bagel from the newest repository and I have got an error like:
 `../../../../src/multi/zcasscf/zcassecond.cc: In member function 'virtual std::shared_ptr<const bagel::ZCoeff_Block> bagel::ZCASSecond_London::semi_canonical_orb() const':
../../../../src/multi/zcasscf/zcassecond.cc:281:42: error: lvalue required as left operand of assignment
   assert((nocc_+nvirt_)*2 = coeff_->mdim())`

I think this part of the code `assert((nocc_+nvirt_)*2 == coeff_->mdim())` should be instead of `assert((nocc_+nvirt_)*2 = coeff_->mdim())` .

Could you check it?
EDIT:
The same typo is on the line 249

**Comment by shiozaki** [comment]
Thanks! The fix is pushed to the master branch. Toru
