### ISSUE TITLE
nh_svp_triplet_gaunt.json crashes

### ISSUE THREAD

**Issue by leos1** [nubakery/bagel#114]
Dear Developers,
  I'm trying to do first steps with using your extremely interesting code.  
I'm using Ubuntu 18.10 with BAGEL v. 1.1.0-1 installed from the standard Ubuntu repository.

However, at present I have problems with running jobs from the "example" directory.
Below you can see output of the "nh_svp_triplet_gaunt.json" job.
It seems that DHF works well, but CASSCF energy (-42540.69020540 - is it energy?) looks strange.
Finally the job crashes.
I had also the same problems with Ubuntu 17/BAGEL 1.0.0.

.....
     9        -54.86986749          0.00000023           0.23
               o DIIS                                        0.00
       - Coulomb: half trans                       0.02
       - Coulomb: metric multiply                  0.12
       - Coulomb: J operator                       0.01
       - Coulomb: K operator                       0.06
               o Fock build                                  0.22
     10        -54.86986750          0.00000003           0.23
  
    * SCF iteration converged.

    * Permanent dipole moment: Dirac Hartree-Fock
           (   -0.000000,    -0.000000,     0.685651) a.u.

    * METHOD: DHF                                  3.11

  ---------------------------
      CASSCF calculation     
  ---------------------------

  *** Geometry (Relativistic) ***
       - 3-index ints post                         0.00
       - 3-index ints prep                         0.00
       - 3-index ints                              0.15
       - 3-index ints post                         0.00
       - 3-index ints prep                         0.00
       - 3-index ints                              0.03
       - 3-index ints post                         0.00

       - Geometry relativistic (total)             0.18

    * nclosed  :      3
    * nact     :      2
    * nvirt    :     33
    * gaunt    : true
    * breit    : false
    * active space: 2 electrons in 2 orbitals
       - Coulomb: half trans                       0.02
       - Coulomb: metric multiply                  0.12
       - Coulomb: J operator                       0.01
       - Coulomb: K operator                       0.06
       - Gaunt: half trans                         0.01
       - Gaunt: metric multiply                    0.07
       - Gaunt: J operator                         0.01
       - Gaunt: K operator                         0.18
 
    ==== Active orbitals : ===== 
         Orbital 4
         Orbital 5
    ============================ 

 
    ==== Active orbitals : ===== 
         Orbital 4
         Orbital 5
    ============================ 

    * nstate   :      3

  === Dirac CASSCF iteration (svp) ===

   * Using the second-order algorithm

         0   0     -42540.69020540     1.00e+03      0.53
         0   1     -42268.23093646     0.00e+00      0.53
         0   2     -42268.23031041     0.00e+00      0.53

         res : 2.57e+04   lamb: 1.00e+00   eps : -1.36e+03   step: 9.81e-01    0.25
         res : 2.58e+04   lamb: 1.00e+00   eps : -1.35e+03   step: 9.97e-01    0.25
         res : 1.54e+04   lamb: 1.00e+00   eps : -1.77e+04   step: 9.28e-01    0.30
         res : 1.57e+04   lamb: 1.00e+00   eps : -1.76e+04   step: 9.35e-01    0.34
         res : 3.71e+03   lamb: 2.85e+00   eps : -2.16e+04   step: 3.70e-01    0.25
         res : 1.26e+04   lamb: 1.00e+00   eps : -2.39e+04   step: 9.73e-01    0.26
         res : 5.21e+02   lamb: 6.08e+00   eps : -2.54e+04   step: 1.62e-01    0.31
         res : 1.62e+02   lamb: 3.89e+00   eps : -2.53e+04   step: 2.50e-01    0.33
         res : 6.02e+01   lamb: 5.97e+00   eps : -2.56e+04   step: 1.64e-01    0.25
         res : 7.79e+00   lamb: 7.28e+00   eps : -2.57e+04   step: 1.35e-01    0.26
         res : 6.11e+00   lamb: 5.88e+00   eps : -2.56e+04   step: 1.66e-01    0.38
         res : 6.37e-01   lamb: 7.18e+00   eps : -2.57e+04   step: 1.36e-01    0.25
         res : 4.74e-01   lamb: 6.29e+00   eps : -2.56e+04   step: 1.56e-01    0.25
         res : 6.90e-01   lamb: 8.38e+00   eps : -2.58e+04   step: 1.17e-01    0.31
         res : 1.45e+00   lamb: 4.74e+00   eps : -2.55e+04   step: 2.06e-01    0.34
         res : 8.95e+00   lamb: 3.47e+00   eps : -2.53e+04   step: 2.81e-01    0.26
         res : 1.93e+01   lamb: 3.12e+00   eps : -2.52e+04   step: 3.13e-01    0.26
         res : 2.70e-01   lamb: 4.04e+00   eps : -2.54e+04   step: 2.41e-01    0.26
         res : 3.36e-02   lamb: 7.79e+00   eps : -2.58e+04   step: 1.26e-01    0.30
  ERROR: EXCEPTION RAISED:  max size reached in AugHess

**Comment by shiozaki** [comment]
That is the problem in the compilation, and not the problem of BAGEL. The energy should be
```
         2   0        -54.93379366     9.43e-07      0.72
         2   1        -54.93378556     0.00e+00      0.72
         2   2        -54.93378556     0.00e+00      0.72
```
Most likely complex functions in BLAS are the problem - please try compelling with Intel MKL, and the problem will likely be gone. I will close the issue.

**Comment by leos1** [comment]
Yes it works with MKL.
Thank you.
