### ISSUE TITLE
--with-boost-libdir still finds boost in system path (and -mt suffix isn't in use anymore)

### ISSUE THREAD

**Issue by Micket** [nubakery/bagel#118]
Two configuration steps are causing problems here:
configure looks for -gcc-mt and -mt suffixes first. These were, as far as I can tell, dropped in boost > 1.60 (unsure about the exact version).

So, despite having a working modern installation and specifying a `--with-boost-libdir=$BOOST_DIR/lib`, configure will always find the `libboost_serialization-mt` from the system paths by default (which in my case happens to be to old).

There is also a difference in the defines used as a result, which even if system paths were excluded, would incorrectly identify "libboost_serialization" as not being mt (it is, in 1.60 and up)

**Comment by shiozaki** [comment]
These are not dropped; they are just not appended in default in the recent releases of Boost.

You could manually alter the order of these in configure.ac. There is no easy way to change this behavior. Will close unless you have a solution within the autoconf/automake framework.

**Comment by Micket** [comment]
Instead of AC_CHECK_LIB, the AX_BOOST_* utilities should be used, as they will respect the result of AX_BOOST, which respects $BOOST_DIR environment variable, so it will behave nicely with HPC environments (where system path installations are impossible)

```m4
AX_BOOST_BASE([1.53], [], [AC_MSG_ERROR("BOOST version >= 1.53.0 required.")])
AX_BOOST_SERIALIZATION
AX_BOOST_REGEX
AX_BOOST_UNIT_TEST_FRAMEWORK
```

**Comment by shiozaki** [comment]
Thanks, I will modify it and test it thoroughly with older versions etc,
and will make a commit later this week.

**Comment by shiozaki** [comment]
Hi Mikael, hope this would work for you. Let me know if it doesn't. Thanks! Toru
