### ISSUE TITLE
error while running Dirac hartree fock

### ISSUE THREAD

**Issue by xubwa** [nubakery/bagel#119]
Dear developers,
I am try to do some relativistic casscf calculation with bagel, when I run the example from the mannual, the job works well when running without mpi, when mpi is being used, it get stucked at the dirack hartree fock step. The error information looks:
`*** Dirac HF ***

       - 1-electron integrals                      0.82
{   -1,   -1}:  On entry to
PDLASRT parameter number    9 had an illegal value
{   -1,   -1}:  On entry to
PDLASRT parameter number    9 had an illegal value`

The compilation configure is gcc/6.1.0, impi/5.1.3.210 mkl/11.3.3 and boost/1.61.0.

Thanks

**Comment by shiozaki** [comment]
How many MPI processes did you use? If you use too many processes for a small calculation, it may not work. Toru

**Comment by xubwa** [comment]
Thank you Toru, I think you are right, it is probably just because the small system and so many mpi processes. Now it is working.
Thanks
