### ISSUE TITLE
Compiling error bagel.1.1.1

### ISSUE THREAD

**Issue by AndreyShtyrov** [nubakery/bagel#120]
Dear, Developers

I have tried install bagel.1.1.1 wiht boost.1.67
I have following errors during installion:

libtool: compile:  mpicxx -DHAVE_CONFIG_H -I. -I../../../../src/util/parallel -I../../.. -I/home/mnryazantsev/local/BOOST/include -I../../../.. -I/home/mnryazantsev/local/BOOST/include -DNDEBUG -std=c++0x -MT process.lo -MD -MP -MF .deps/process.Tpo -c ../../../../src/util/parallel/process.cc -o process.o
libtool: compile:  mpicxx -DHAVE_CONFIG_H -I. -I../../../../src/util/parallel -I../../.. -I/home/mnryazantsev/local/BOOST/include -I../../../.. -I/home/mnryazantsev/local/BOOST/include -DNDEBUG -std=c++0x -MT mpi_interface.lo -MD -MP -MF .deps/mpi_interface.Tpo -c ../../../../src/util/parallel/mpi_interface.cc -o mpi_interface.o
libtool: compile:  mpicxx -DHAVE_CONFIG_H -I. -I../../../../src/util/parallel -I../../.. -I/home/mnryazantsev/local/BOOST/include -I../../../.. -I/home/mnryazantsev/local/BOOST/include -DNDEBUG -std=c++0x -MT rmawindow.lo -MD -MP -MF .deps/rmawindow.Tpo -c ../../../../src/util/parallel/rmawindow.cc -o rmawindow.o
libtool: compile:  mpicxx -DHAVE_CONFIG_H -I. -I../../../../src/util/parallel -I../../.. -I/home/mnryazantsev/local/BOOST/include -I../../../.. -I/home/mnryazantsev/local/BOOST/include -DNDEBUG -std=c++0x -MT resources.lo -MD -MP -MF .deps/resources.Tpo -c ../../../../src/util/parallel/resources.cc -o resources.o
In file included from ../../../../src/util/parallel/resources.cc:25:
../../../../src/util/parallel/resources.h:32:18: error: atomic: No such file or directory
In file included from /usr/local/intel/impi/4.0.3.008/intel64/include/mpi.h:1221,
                 from ../../../../src/util/parallel/rmawindow.h:32,
                 from ../../../../src/util/parallel/rmawindow.cc:28:
/usr/local/intel/impi/4.0.3.008/intel64/include/mpicxx.h:93:2: error: #error "SEEK_SET is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"
/usr/local/intel/impi/4.0.3.008/intel64/include/mpicxx.h:97:2: error: #error "SEEK_CUR is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"
/usr/local/intel/impi/4.0.3.008/intel64/include/mpicxx.h:102:2: error: #error "SEEK_END is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"
In file included from /usr/local/intel/impi/4.0.3.008/intel64/include/mpi.h:1221,
                 from ../../../../src/util/parallel/mpi_interface.h:36,
                 from ../../../../src/util/parallel/process.cc:27:

........

../../../../src/util/parallel/rmawindow.cc:328: error: ‘MPI_Rput’ was not declared in this scope
make[4]: *** [mpi_interface.lo] Error 1
make[4]: *** [rmawindow.lo] Error 1
make[4]: Leaving directory `/home/mnryazantsev/bagel-1.1.1/obh/src/util/parallel'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/mnryazantsev/bagel-1.1.1/obh/src/util'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/mnryazantsev/bagel-1.1.1/obh/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/mnryazantsev/bagel-1.1.1/obh'
make: *** [all] Error 2

**Comment by shiozaki** [comment]
It seems that your gcc and mpi are too old. Please check that gcc is c++11 complete and mpi supports mpi3. Toru

On Jun 7, 2018, at 7:34 PM, AndreyShtyrov <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear, Developers

I have tried install bagel.1.1.1 wiht boost.1.67
I have following errors during installion:

libtool: compile: mpicxx -DHAVE_CONFIG_H -I. -I../../../../src/util/parallel -I../../.. -I/home/mnryazantsev/local/BOOST/include -I../../../.. -I/home/mnryazantsev/local/BOOST/include -DNDEBUG -std=c++0x -MT process.lo -MD -MP -MF .deps/process.Tpo -c ../../../../src/util/parallel/process.cc<http://process.cc> -o process.o
libtool: compile: mpicxx -DHAVE_CONFIG_H -I. -I../../../../src/util/parallel -I../../.. -I/home/mnryazantsev/local/BOOST/include -I../../../.. -I/home/mnryazantsev/local/BOOST/include -DNDEBUG -std=c++0x -MT mpi_interface.lo -MD -MP -MF .deps/mpi_interface.Tpo -c ../../../../src/util/parallel/mpi_interface.cc<http://mpi_interface.cc> -o mpi_interface.o
libtool: compile: mpicxx -DHAVE_CONFIG_H -I. -I../../../../src/util/parallel -I../../.. -I/home/mnryazantsev/local/BOOST/include -I../../../.. -I/home/mnryazantsev/local/BOOST/include -DNDEBUG -std=c++0x -MT rmawindow.lo -MD -MP -MF .deps/rmawindow.Tpo -c ../../../../src/util/parallel/rmawindow.cc<http://rmawindow.cc> -o rmawindow.o
libtool: compile: mpicxx -DHAVE_CONFIG_H -I. -I../../../../src/util/parallel -I../../.. -I/home/mnryazantsev/local/BOOST/include -I../../../.. -I/home/mnryazantsev/local/BOOST/include -DNDEBUG -std=c++0x -MT resources.lo -MD -MP -MF .deps/resources.Tpo -c ../../../../src/util/parallel/resources.cc<http://resources.cc> -o resources.o
In file included from ../../../../src/util/parallel/resources.cc:25<http://resources.cc:25>:
../../../../src/util/parallel/resources.h:32:18: error: atomic: No such file or directory
In file included from /usr/local/intel/impi/4.0.3.008/intel64/include/mpi.h:1221,
from ../../../../src/util/parallel/rmawindow.h:32,
from ../../../../src/util/parallel/rmawindow.cc:28<http://rmawindow.cc:28>:
/usr/local/intel/impi/4.0.3.008/intel64/include/mpicxx.h:93:2: error: #error "SEEK_SET is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"
/usr/local/intel/impi/4.0.3.008/intel64/include/mpicxx.h:97:2: error: #error "SEEK_CUR is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"
/usr/local/intel/impi/4.0.3.008/intel64/include/mpicxx.h:102:2: error: #error "SEEK_END is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"
In file included from /usr/local/intel/impi/4.0.3.008/intel64/include/mpi.h:1221,
from ../../../../src/util/parallel/mpi_interface.h:36,
from ../../../../src/util/parallel/process.cc:27<http://process.cc:27>:

........

../../../../src/util/parallel/rmawindow.cc:328<http://rmawindow.cc:328>: error: 'MPI_Rput' was not declared in this scope
make[4]: *** [mpi_interface.lo] Error 1
make[4]: *** [rmawindow.lo] Error 1
make[4]: Leaving directory /home/mnryazantsev/bagel-1.1.1/obh/src/util/parallel' make[3]: *** [all-recursive] Error 1 make[3]: Leaving directory/home/mnryazantsev/bagel-1.1.1/obh/src/util'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory /home/mnryazantsev/bagel-1.1.1/obh/src' make[1]: *** [all-recursive] Error 1 make[1]: Leaving directory/home/mnryazantsev/bagel-1.1.1/obh'
make: *** [all] Error 2

-

**Comment by AndreyShtyrov** [comment]
Yes, I have checked gcc and mpi, and they are not satisfy requirements.

Thanks for the help.

**Comment by AndreyShtyrov** [comment]
I have try compile bagel on another machine with intel 2017.1 with  intel mpi but it fault with this error.

../../../../src/util/parallel/mpi_interface.cc(236): error: class "std::map<int, std::vector<MPI_Request={int}, std::allocator<MPI_Request={int}>>, std::less<int>, std::allocator<std::pair<const int, std::vector<MPI_Request={int}, std::allocator<MPI_Request={int}>>>>>" has no member "emplace"
    request_.emplace(cnt_, rq);
             ^
