### ISSUE TITLE
Visually pick the orbital for relativistic casscf

### ISSUE THREAD

**Issue by xubwa** [nubakery/bagel#123]
Dear all,
I am working on a RelCASSCF calculation, the orbital specified by counting the number is not quite good. Is there any way to visually or manually pick the orbital?

**Comment by shiozaki** [comment]
Use cube file to visualize them.

**Comment by jesusG-V** [comment]
Concerning this question, is there a way to create different cubes for the real and imaginary part so that the phase can also be visualized or maybe two molden files?

**Comment by shiozaki** [comment]
Short answer is no. Visualizing real and imaginary part separately is not a good idea, because they vary arbitrarily as you multiply some phase factors.

**Comment by jesusG-V** [comment]
I can understand that, but the phase is very important to undestand the shape of the orbitals, so maybe creating a cube file with the phase?

**Comment by shiozaki** [comment]
In any case I'm afraid we don't have manpower to do this. You are welcome to work on it.

FYI: the right thing to do is to use rgb spectrum to represent the phase. See mathematica. This requires updating a visualizer as well.

On Aug 8, 2018, at 4:16 AM, Jes?s Gonz?lez-V?zquez <notifications@github.com<mailto:notifications@github.com>> wrote:


I can understand that, but the phase is very important to undestand the shape of the orbitals, so maybe creating a cube file with the phase?

-
