### ISSUE TITLE
Cannot build Bagel: MKL not found

### ISSUE THREAD

**Issue by IIoffe** [nubakery/bagel#125]
Hello,

My attempts to configure Bagel terminate prematurely with 

checking for main in -lmkl_intel_lp64... no
configure: error: Cannot find Intel Math Kernel Library

Fresh MKL is installed and the library folders are explicitly included in the LD_LIBRARY_PATH

I'd greatly appreciate any suggestions.
Best regards
Ilya

**Comment by shiozaki** [comment]
OK it's a bug in old gcc https://gcc.gnu.org/bugzilla/show_bug.cgi?id=48891

Can you change line 227 in src/smith/spinfreebase.cc to 
```
const bool dothis = !::isnan(cap[0]);
``
and see if it works? (i.e., adding "::")

**Comment by IIoffe** [comment]
Dear Toru,

Thank you, now everything seems fine
