### ISSUE TITLE
Optimization stop in the end of hessian calculation

### ISSUE THREAD

**Issue by AndreyShtyrov** [nubakery/bagel#127]
I have tried to make transition state optimizaition, but job ended atfre last calcutation gradient in order to calculate hessian. 

...
{
"title" : "optimize",
"target" : 0,
"opttype" : "transition",
"hess_approx" : false,
"method" : [ {
"title" : "caspt2",
"smith" : {
"method" : "caspt2",
"shift" : 0.25,
"frozen" : true
},
"nstate" : 1,
"nact" : 10,
"nclosed" : 22
} ]
},
...

**Comment by jwpk1201** [comment]
Hi Andrey,

Could you provide full input and output files at triplepjw@gmail.com to investigate the problem?

Sincerely,
Jae Woo
