### ISSUE TITLE
Showing charges

### ISSUE THREAD

**Issue by AndreyShtyrov** [nubakery/bagel#131]
Dear community of BAGEL.
Where can i find charges for each states in MS-CASSCF, and oscillator strength ?

Thanks,

**Comment by jwpk1201** [comment]
Hi Andrey,

The oscillator strengths between any states are printed by performing derivative coupling calculations between these states. Could you please tell me what do you mean by "charges," are they atomic charges (e.g. Mulliken charges)? The atomic charges are not implemented in BAGEL by default.

Jae Woo

**Comment by AndreyShtyrov** [comment]
Yes, I mean atomic charges.
