### ISSUE TITLE
mich should be among --with-mpi={mpi-type} values?

### ISSUE THREAD

**Issue by yurivict** [nubakery/bagel#132]
I supplies ```--with-mpi=openmpi```, and it got linked with ```libmpicxx.so``` from ```mpich``` despite ```mpich``` not being listed in ```configure.ac``` as a possible value of ```--with-mpi```.

This raises these questions:
* This is a bug that ```--with-mpi=openmpi``` links with ```mpich```.
*  Should ```mpich``` be added as a value to ```configure.ac``` ? Is it supported?

**Comment by shiozaki** [comment]
Specify MVAPICH. I try to discourage using MVAPICH in the environment where fast interconnect is available (where BAGEL is supposed to be used).

**Comment by yurivict** [comment]
But you shouldn't link with ```mpich``` when ```--with-mpi=openmpi``` is supplied. This doesn't look right. You should either support all values: ```mpich```, ```openmpi```, ```mvapich```, or disallow them.

**Comment by shiozaki** [comment]
The library that is to be linked is determined by the compiler (not by BAGEL), which I think is the right behavior. You probably have mpicxx in PATH that is openmpi.

This parameter is only used for MKL libraries (see configure.ac). BAGEL does not automatically pick MPI executables/libraries, but rather it is asking people to specify what MPI they have in PATH.

**Comment by yurivict** [comment]
> You probably have mpicxx in PATH that is openmpi.

```mpicxx``` executables are installed by both ```mpich``` and ```openmpi```. They are at different paths. So I guess both ```mpich``` and ```openmpi``` should be supported then.

**Comment by yurivict** [comment]
"which mpicxx" depends on the path. Path can be changed such that either ```mpich``` or ```openmpi``` can be picked.
