### ISSUE TITLE
Spin purity in CASSCF

### ISSUE THREAD

**Issue by IIoffe** [nubakery/bagel#136]
Dear Toru,

I'm trying to do SA6-CASSCF for the singlet states of one stilbene molecule. It turns out that every CI step eventually brings in 1-2 triplet roots, and explicit nspin=0 does not seem to help. How could I enforce the desired spin purity?

Best regards,

Ilya

**Comment by shiozaki** [comment]
Hi Ilya,

I am happy to help - Can you send me an input to shiozaki.toru@gmail.com (I will close this issue in the mean time) so that I can trouble shoot? I thought that the spin purification is always performed in non-rel calculations but may be that I don't remember correctly.

Toru
