### ISSUE TITLE
Different dipole moments in Bagel and MOLCAS (SHARC-Bagel interface)

### ISSUE THREAD

**Issue by AlexPrihodko** [nubakery/bagel#137]
Dear all,

I'm writing an interface for SHARC and Bagel interaction and I got problem that if I take the same geometry (for calculation using MOLCAS and Bagel), I get the same gradients, but also I get different dipole moments (they also don't differ by a constant when multiplied). 
With what it can be connected?

Thanks,

**Comment by shiozaki** [comment]
It's unclear so you should ask Molcas people. BAGEL's dipole is checked against finite difference calculations using finite electric field. In other words, it is strictly energy derivative with respect to E field. The expansion center is the charge center as it should. I close this issue.

**Comment by shiozaki** [comment]
PS: if you have questions, please send me an input and output to shiozaki.toru@gmail.com. I want to reserve this "issues" on the repository for issues. Thanks.
