### ISSUE TITLE
DKHgrad failure

### ISSUE THREAD

**Issue by jesusG-V** [nubakery/bagel#138]
Dear all,

I am trying a calculation using Douglas-Kroll Hamiltonian and I found a problem in the gradient subroutine. Sending the calculation without DKH, it works fine and a similar result is obtained using numerical gradients with DKH. However, when using analytical gradients, the results are not good... I just upload an example using mp2 in the HB r molecule.

In the zip, UI send the following data:
mp2-cc -> No DKH result
mp2-cc-dkh -> dkh with analytical gradients, the gradients in the x and y directions must be zero
mp2-cc-dkh-num -> dkh with numerical gradients

[mp2-cc.zip](https://github.com/nubakery/bagel/files/2525220/mp2-cc.zip)

**Comment by shiozaki** [comment]
Thanks for reporting this - I reproduced the error. Will take a look now.

**Comment by shiozaki** [comment]
Hi Jesus, thanks again for the report. I fixed it in the most recent commit to the master branch (the program was reading an uninitialized member variable that caused the issue). Please check out and see if it works. Cheers

**Comment by jesusG-V** [comment]
It works fine now.

Thanks a lot!!!
