### ISSUE TITLE
Point Charge Embedding

### ISSUE THREAD

**Issue by vamshimohank** [nubakery/bagel#139]
Hello,

Is there a way to include point charges from an external file? Specifying the dummy atom  in the geometry block is convenient for few point charges, but if I have few thousands of them that form an embedding to a cluster of atoms, it would be beneficial to specify the point charges separately from the geometry block.

Is there a feature like this ? 

Thanks and regards
Vamshi

**Comment by shiozaki** [comment]
Hi Vamshi,

Thanks for your question. There is no another mechanism to include these embedding charges in the input. This is how the data are stored internally in the Molecule class in BAGEL, so it does not make sense to make another way. You could write a script to generate BAGEL inputs.

If the number of point charges is too large that you start to see the IO overhead when you run a calculation, I suggest to use the following way of running BAGEL (-i option). In short, BAGEL's input does not have to be written on disk; all you have to do is to write a python script that parse your point charges and write in a JSON object, and use that to start a BAGEL process.

```
BAGEL -i "{\"bagel\":[{\"title\":\"molecule\",\"basis\":\"svp\",\"df_basis\":\"svp-jkfit\",\"angstrom\":\"false\",\"geometry\":[{\"atom\":\"F\",\"xyz\":[-0.000000,-0.000000,2.720616]},{\"atom\":\"H\",\"xyz\":[-0.000000,-0.000000,0.305956]}]},{\"title\":\"hf\",\"thresh\":1.0e-10}]}"
```

Please pull the latest master branch before testing this.

I will close the issue.

Best,
Toru

**Comment by vamshimohank** [comment]
Dear Toru,

Thanks for providing a way to do it. I will try it out. 

BTW, I have a related issue: When you have system with point charges and try to read a molden file for the starting orbitals e.g. to do a post-HF calculation, because the molden file do not store the charges, one is unable to read the orbitals. I might be wrong, but the program quits with segmentation fault while reading the geometry and orbitals from the molden file. 

Regards
Vamshi

**Comment by WANGBO428** [comment]
HELLO,
I don‘t know how to add point charge.
In bagel user manunal, I saw finite_nuclues keywords can represent charge distribution,but I can't understand,if a value of 0.0 indicates a point charge,so how should the value of the point charge be expressed?
For the simplest input file, how to add a point charge?
{ "bagel" : [
{
  "title" : "molecule",
  "basis" : "svp",
  "df_basis" : "svp-jkfit",
  "angstrom" : "false",
  "geometry" : [
    { "atom" : "Cl",  "xyz" : [ -0.000000,     -0.000000,      2.720616]},
    { "atom" : "H",  "xyz" : [ -0.000000,     -0.000000,      0.305956]}
  ]
},
{
  "title" : "hf",
  "thresh" : 1.0e-10
}
]}
Thanks and regards
WangBo

**Comment by xubwa** [comment]
Hi,
Finite nucleus model is not related to this question, it is related to the charge model of the nuclear. For point charge embedding you can look at the dummy atom keyword.
Best,
Xubo

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
