### ISSUE TITLE
Oscillator strength for several electronic states

### ISSUE THREAD

**Issue by dpvalverde** [nubakery/bagel#140]
Dear,

I am a beginner user of the Bagel program. I would like to calculate the oscillator strength from S0 to S1, S0 to S2 and so on. However, the default is to compute a single oscillator strength between the S0 and S1 states. How can I calculate the oscillator strength for several electronic states? 

Thanks
Danillo

**Comment by jwpk1201** [comment]
Hi Danillo,

You can compute oscillator strength for all the pairs between the states by specifying the keyword "dipole" : "true" in any kind of gradient calculations, For example,

...
{
  "title" : "force",
  "target" : 0,
  "dipole" : true,
...

If there are 4 states, BAGEL computes the oscillator strength for the states 0 - 1, 0 - 2, 0 - 3, 1 - 2, 1 - 3, and 2 - 3.

Sincerely,
Jae Woo

**Comment by dpvalverde** [comment]
Dear Park,

Thank you for your answer. I had not seen this keyword. I tested here and the oscillator strength are printed. 

I have another question: What about IPEA correction in CASPT2? Nowhere in manual is mentioned about it. 

Best regards,
Danillo

**Comment by shiozaki** [comment]
Hi Danillo,

Bagel doesn’t implement IPEA shifts now and in the near future. Thanks,

Toru

**Comment by jwpk1201** [comment]
Hi Danillo,

This message indicates that the CASSCF iteration did not converge. Maybe the structure was too distorted during the iteration. I think there are two ways to circumvent this problem:

(a) increase the keyword "maxiter" (the default is 50), so that the CASSCF iteration can converge after some iterations.
(b) start over from the converged XMS-CASPT2 structure. I think that the MS-CASPT2 geometry is near the XMS-CASPT2 geometry, so it would make better initial guess for geometry optimization.

Sincerely,
Jae Woo

**Comment by dpvalverde** [comment]
Hi,

I increased the number of iteration in the CASSCF module and I started from the converged XMS-CASPT2 structure. I had the same message. Furthermore, the grad rms is floating around a high value, even after 13 iterations. Attached I put the input and output files.
[bagel.zip](https://github.com/nubakery/bagel/files/2612657/bagel.zip)

Best regards,
Danillo

**Comment by jwpk1201** [comment]
Hi Danillo,

In your output, I can see that the Z-vector equation for the gradient did not converge for MS-CASPT2. I am now trying to understand why this happens (probably because the source term for MS-CASPT2 is usually too large...)

Jae Woo

**Comment by shiozaki** [comment]
I think CASPT2 gradients should be always used with xms=true. MS-CASPT2 is an ill defined theory and gradients are unstable. Toru
