### ISSUE TITLE
BAGEL 1.2.0 parallel runs stuck

### ISSUE THREAD

**Issue by vborin** [nubakery/bagel#141]
Dear BAGEL developers,

I compiled the most recent BAGEL (Intel 2019 MPI, MKL, Ubuntu 16.04.5 x64).
If I call just _$ BAGEL input > output_ the job ends normally but once I try _$ mpirun -np 48 BAGEL input > output_, it gets stuck forever (see the attached output file).
[bagel.txt](https://github.com/nubakery/bagel/files/2607509/bagel.txt)

Could you please help me to solve this issue?

Thanks in advance!

Regards,
Veniamin

**Comment by shiozaki** [comment]
Also I see that you are running 48 MPI processes and each process is using
48 threads; in otherwise you have 48x48 threads running now. You should set
BAGEL_NUM_THREADS and MKL_NUM_THREADS to adjust the number of threads.

**Comment by vborin** [comment]
Hi Toru,

Thank you very much! I'll try the new setup as soon as the node will be available and tell you the result.

Veniamin

**Comment by vborin** [comment]
Hi Toru,

I just tried adjusting BAGEL_NUM_THREADS and MKL_NUM_THREADS along with changing _-np_ flag. However, I have same problem (see the outputs attached).
[bagel.2.txt](https://github.com/nubakery/bagel/files/2610188/bagel.2.txt)
[bagel.32.txt](https://github.com/nubakery/bagel/files/2610189/bagel.32.txt)

Warmest regards,
Veniamin

**Comment by vborin** [comment]
Hi Toru,
I found that the main problem was in the old Intel compiler. With the newest version everything works fine! 

Regards,
Veniamin

**Comment by shiozaki** [comment]
Great!
