### ISSUE TITLE
How can I export an orbital file in each iteration of the geometry optimization

### ISSUE THREAD

**Issue by dpvalverde** [nubakery/bagel#149]
Hi everyone,

I am performing a geometry optimization at the XMS-CASPT2 level of theory. I would like to export the orbitals file and the molden file in each iteration. Is there an easy way to do this in Bagel program? I would like to check if the active space is correct. 

Best regards,
Danillo Valverde

**Comment by shiozaki** [comment]
Can you do the following quick hack (adding 5 lines with "+" after line 144) and see if you are getting what you want?
```
diff --git a/src/opt/opt.cc b/src/opt/opt.cc
index 8b5fb1269..5239b042b 100644
--- a/src/opt/opt.cc
+++ b/src/opt/opt.cc
@@ -144,6 +144,11 @@ void Opt::print_iteration(const int iter, const double residual, const double pa
     print_iteration_energy(iter, residual, time);
   }
   print_history_molden();
+
+  stringstream ss; ss << "geom" << iter << ".molden";
+  MoldenOut m(ss.str());
+  m << prev_ref_->geom();
+  m << prev_ref_;
 }
```

**Comment by shiozaki** [comment]
I implemented the above code and pushed to the master (b062784b5cae78456105122111499ded47a3c2be). You should be able to print out the molden files if you set "molden" : true  in the "optimize" block (see the updated manual).

Let me close the issue - if you see some wrong behavior, let me know.

Toru

**Comment by dpvalverde** [comment]
Dear Toru,

I will try to install bagel program again. Thank you for your attention.

Best regards,
Danillo

Em ter, 22 de jan de 2019 às 14:54, Toru Shiozaki <notifications@github.com>
escreveu:
