### ISSUE TITLE
bagel aborts with error "unregistered class"

### ISSUE THREAD

**Issue by oivulf** [nubakery/bagel#151]
git bagel compiled with boost-1.67 aborts during some kinds of computation.
The error:
  ERROR: EXCEPTION RAISED:  unregistered class
seems to me bound to some missing registration in boost-serialization.
I attach one input aborting together with the relevant log.

[benzoquinone_10PT2_B3gff.log](https://github.com/nubakery/bagel/files/2836398/benzoquinone_10PT2_B3gff.log)

[benzoquinone_10PT2_B3gff.json.txt](https://github.com/nubakery/bagel/files/2836402/benzoquinone_10PT2_B3gff.json.txt)

**Comment by shiozaki** [comment]
Can you give me the input including the one that generated the reference file? If you could give me an example with a small molecule, I could build BAGEL with boost 1.67 and try fix it.

**Comment by oivulf** [comment]
Dear shiozaki,
actually I also compiled bagel with boost 1.62 and had a similar problem.
The reference comes from a cascade of calculations, if needed I can pass them all to you.

  ===============================================================
    BAGEL - Freshly leavened quantum chemistry                   
  ===============================================================

       - 3-index ints prep                         0.01
       - 3-index ints                              0.07
       - 2-index ints                              0.00
       - computing inverse                         0.51
[node13:25080] *** Process received signal ***
[node13:25080] Signal: Segmentation fault (11)
[node13:25080] Signal code: Address not mapped (1)
[node13:25080] Failing at address: (nil)
[node13:25080] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12670)[0x7fd991a15670]
[node13:25080] [ 1] /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.62.0(+0x17652)[0x7fd99212b652]
[node13:25080] [ 2] /cluster/share/bagel/lib/libbagel.so.0(_ZNK5boost7archive6detail11iserializerINS0_15binary_iarchiveESt10shared_ptrIKN5bagel6CIWfn_INS5_7DvectorIdEENS5_12DeterminantsEEEEE16load_object_dataERNS1_14basic_iarchiveEPvj+0x7f)[0x7fd9948c75ef]
[node13:25080] [ 3] /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.62.0(_ZN5boost7archive6detail14basic_iarchive11load_objectEPvRKNS1_17basic_iserializerE+0x13b)[0x7fd99212aecb]
[node13:25080] [ 4] /cluster/share/bagel/lib/libbagel.so.0(_ZNK5boost7archive6detail11iserializerINS0_15binary_iarchiveEN5bagel9ReferenceEE16load_object_dataERNS1_14basic_iarchiveEPvj+0x265)[0x7fd9948c1565]
[node13:25080] [ 5] /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.62.0(_ZN5boost7archive6detail14basic_iarchive11load_objectEPvRKNS1_17basic_iserializerE+0x192)[0x7fd99212af22]
[node13:25080] [ 6] /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.62.0(+0x1781c)[0x7fd99212b81c]
[node13:25080] [ 7] /cluster/share/bagel/lib/libbagel.so.0(_ZNK5boost7archive6detail11iserializerINS0_15binary_iarchiveESt10shared_ptrIN5bagel9ReferenceEEE16load_object_dataERNS1_14basic_iarchiveEPvj+0x6c)[0x7fd9948beefc]
[node13:25080] [ 8] /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.62.0(_ZN5boost7archive6detail14basic_iarchive11load_objectEPvRKNS1_17basic_iserializerE+0x13b)[0x7fd99212aecb]
[node13:25080] [ 9] /cluster/share/bagel/lib/libbagel.so.0(_ZN5bagel8IArchiversISt10shared_ptrINS_9ReferenceEEEERS0_RT_+0x4a)[0x7fd9948bc8aa]
[node13:25080] [10] /cluster/share/bagel/lib/libbagel.so.0(_ZN5bagel4impl10run_bagel_ESt10shared_ptrIKNS_5PTreeEE+0x131a)[0x7fd99489268a]
[node13:25080] [11] /cluster/share/bagel/lib/libbagel.so.0(_ZN5bagel20run_bagel_from_inputERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x68)[0x7fd994894558]
[node13:25080] [12] /cluster/share/bagel/bin/BAGEL(+0xcebd)[0x560ed949febd]
[node13:25080] [13] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7fd99141d09b]
[node13:25080] [14] /cluster/share/bagel/bin/BAGEL(+0xcfda)[0x560ed949ffda]

**Comment by shiozaki** [comment]
Please make an example that is small enough for testing and post it here. The code is working fine with 1.68. There is also a possibility that your runtime environment is different from that in which you compiled BOOST and BAGEL. The BOOST serialization is basically not compatible between different BOOST versions and between BOOST builds with different compilers.

**Comment by oivulf** [comment]
Well, the problem was due to archive files having been produced with an older version of bagel, 1.1.5 I think. I guess there was some refactoring of classes in the middle bringing to incompatibility.
Sorry for annoying.
Please close the ticket.

**Comment by shiozaki** [comment]
No problem!
