### ISSUE TITLE
CASPT2 frequency calculation with parallelization

### ISSUE THREAD

**Issue by jwpk1201** [nubakery/bagel#152]
CASPT2 frequency calculation with an embarrassingly parallel mode hangs with a large number of determinants (Ndet > 1000). It seems that the hang occurs in the following procedure:

(1) BAGEL splits the whole process into the (nmpi) separate MPI communicators. (depth = 1)
(2) In the CASPT2 gradient code, BAGEL splits each process into (nprocs) MPI communicators again when there are more than 1,000 determinants and nprocs > 1. (depth = 2)
(3) After CASPT2 gradient calculation (more specifically, CI derivative contraction) is finished, BAGEL merges the MPI communicators again. (depth = 1)
(4) When all gradient calculations are done, all the MPI communicators are merged. (depth = 0)

However, when (natom X 3 % nmpi) != 0, some of the (nmpi) communicators, which do not have assignments anymore, is already at the stage (4), and when the other processes are trying to perform (3), BAGEL hangs, perhaps because the processes at the stage (4) thinks that they were also to be merged.

I am working on debugging this.

**Comment by jwpk1201** [comment]
Update: Seems like blacs_gridmap_ blocks globally (MPI_COMM_WORLD), and it hangs until all the processes call this routine. In our case, this happens only when (natomX3%nmpi) == 0. Some people are complaining about this in forums, but I assume this behavior is somewhat intended in SCALAPACK. we should find a way to circumvent this problem...

**Comment by shiozaki** [comment]
If that's the case, can't we make a comm world for the rest of the MPI processes and call blacs_gridmap_ from there? That residual comm world does not have to be used at all.

**Comment by jwpk1201** [comment]
OK, I think I can implement a way to circumvent it.

**Comment by jwpk1201** [comment]
This is debugged; I will close this issue now.
