### ISSUE TITLE
Optimizaton this 

### ISSUE THREAD

**Issue by AlexPrihodko** [nubakery/bagel#153]
Hello,

I'm trying to do caspt2 optimization with external charge. But there is the problem of changing the coordinates of the charge relative to the molecule. If I write keyword "internal" : true, the error appears: "haven't thought about internal coordinate with dummy atoms (or gradient in general)" 
How I can enter the correct options to fix the charge relative to the center of mass and the plane of the molecule?

Thanks,

**Comment by jwpk1201** [comment]
Hi Alex,

Currently, the optimization routine with "internal" : "true" does not support the presence of dummy atoms. You can optimize the structure without the internal coordinate (i.e. use Cartesian coordinates in optimization) when there is an external charge. When there are two or more external charges, the electrostatic interactions between the external charges can be turned on or off by the keyword "skip_self_interaction" (see https://nubakery.org/molecule/molecule.html?highlight=skip_self_interaction).

Sincerely,
Jae Woo

**Comment by shiozaki** [comment]
Hi Jae Woo, if this behavior is documented in the manual, please close the issue. Otherwise, please make a pull request to the manual repo with the changes. Thanks! Toru

**Comment by jwpk1201** [comment]
Hi Toru,

 

I just updated the manual!

 

Jae Woo
