### ISSUE TITLE
the using "explicitbond"

### ISSUE THREAD

**Issue by valievrashid** [nubakery/bagel#154]
I am trying to optimize the cluster of two molecules and receive the message:
"  ERROR: EXCEPTION RAISED:  Internal coordinate transformation currently requires that we have only one molecule,  -- consider using "explicitbond" . I set "internal": false according to the manual when we deal with non single molecule. However, it didn't help. I couldn't find any information about how to use or set "explicitbond". Could you explain me how to do it? 
Thank you very much!

**Comment by shiozaki** [comment]
Thanks for your comment, I asked Jae Woo, who wrote a code to follow up with an example.

**Comment by jwpk1201** [comment]
Hi,

You can use the keyword "explicitbond" : true and a group of keywords "explicit" in "title" : "optimize". For example,

{
  "title" : "optimize",
  "explicitbond" : true,
  "explicit" : [
    { "pair" : [1, 5]},
    { "pair" : [2, 12]}
  ],
  "method" : [ {
    "title" : "hf"
  } ]
},
will add two "explicit" bonds between two pairs of non-bonded atoms, (1, 5) and (2, 12). (Note that these atomic indices are of course 1-based)

On the side note, if you are optimizing the geometry of a molecular cluster, you can also try "internal" : "false" with a smaller "maxstep".

Jae Woo

**Comment by valievrashid** [comment]
Thank you very much! Now it works properly! It is excellent software!

**Comment by valievrashid** [comment]
And last question. Is it possible to use the CASPT2 method to find the transition state using the  analytical hessian and gradient? 
Thank you!

**Comment by shiozaki** [comment]
There is no analytical CASPT2 Hessian implemented in BAGEL. However, Hessian can be computed using finite difference of analytical gradients. I will close this issue.

@jwpk1201 can you add more information if any? Thanks

**Comment by valievrashid** [comment]
Hello!
Thank you for the useful information. And one question about the hessian
analysis. As I understand the numerical hessian calculation shows always
"0" for the rotational and translational frequencies. So If I have number 6
frequency is not zero that is imaginary or not? How can we understand that
we obtain the imaginary frequency? Usually, the imaginary unity (i) mark
it, but I can't see here.
Thank you very much for the answer!

ср, 27 мар. 2019 г. в 23:04, Toru Shiozaki <notifications@github.com>:

**Comment by jwpk1201** [comment]
Hi Valiev,

the imaginary frequencies are displayed as negative numbers in BAGEL.

Sincerely,
Jae Woo

**Comment by valievrashid** [comment]
Thank, Jae Woo!
But, another question. I am trying to find the transition state using
CASPT2. The initial hessian was calculated numerically and I could see the
imaginary frequency (-183). After it, the gradient was calculated and then
the task was ended without any information about the successfully or not
calculation. So, I can't check the shape of mode and etc. I inserted my
input file  and output file for your fast answer.
Thank you very much! We plan to use BAGEL in all our calculations.


пн, 1 апр. 2019 г. в 11:14, Jae Woo Park <notifications@github.com>:

**Comment by shiozaki** [comment]
I think the attachment has been stripped away by Github. Could you write an email to Jae Woo (triplepjw@gmail.com) and me (shiozaki.toru@gmail.com) directly with the attachment?

**Comment by valievrashid** [comment]
Dear Toru and Jae Woru!
The files are attached.
Thank you very much!
Best regards, Rashid.
P.S.
 Thank, Jae Woo!

But, another question. I am trying to find the transition state using
CASPT2. The initial hessian was calculated numerically and I could see the
imaginary frequency (-183). After it, the gradient was calculated and then
the task was ended without any information about the successfully or not
calculation. So, I can't check the shape of mode and etc. I inserted my
input file  and output file for your fast answer.

Thank you very much! We plan to use BAGEL in all our calculations.

вт, 2 апр. 2019 г. в 22:55, Toru Shiozaki <notifications@github.com>:

**Comment by valievrashid** [comment]
Dear Toru and Jae Woru!
Did you receive the input and output files?
Best regards, Rashid.

ср, 3 апр. 2019 г. в 12:33, Rashid Valiev <valievrashid@gmail.com>:

**Comment by jwpk1201** [comment]
Hi Rashid,

Yes, I got the input file and tried to run it in my computer. It goes through the point that the job was dead, and I am testing it to reproduce the error using various conditions. I will keep you posted.

Jae Woo
