### ISSUE TITLE
nclosed value

### ISSUE THREAD

**Issue by ethan0879** [nubakery/bagel#156]
Hi,
What is the meaning of closed orbitals? I mean for benzene, it is 18 according to the example. Why? How should I choose this value? If I run the input using the default nclosed value (number of electrons / 2), the calculation just crashes with a segmentation fault message. Thanks in advance!

**Comment by shiozaki** [comment]
In CASSCF, you need to specify the number of closed orbitals (doubly occupied) and active orbitals (partially occupied). The choice of active spaces is non trivial, usually based on chemical intuition. Please look for some literature to learn some of it.
