### ISSUE TITLE
Max iteration reached during the second-order optimization.

### ISSUE THREAD

**Issue by ethan0879** [nubakery/bagel#157]
When I was doing CASPT2 optimizations, I got the following error,

Max iteration reached during the second-order optimization.

It is not clear to me which keyword I should include to increase the iterations.

**Comment by shiozaki** [comment]
It most likely indicates that your active spaces is not properly defined. Increasing the number of iteration is not the solution to your problem at hand.

Please use this form only for bug reports. Thanks.

**Comment by warin-wrt** [comment]
I have same problem "ERROR: EXCEPTION RAISED:  Max iteration reached during the second-order optimization" in BAFEL. How can I solve it.
