### ISSUE TITLE
CASSCF bug?

### ISSUE THREAD

**Issue by ethan0879** [nubakery/bagel#158]
Hi,
When running a CASSCF calculation using an active space of 18 in 18, the calculation does not detect the right active space. Instead, I got that configuration
2222222222222222..

And it should be 222222222.........

I revised the active space thousand times and, even I changed the active space.

I think that is a bug. Isn't it?

Thanks!

**Comment by shiozaki** [comment]
No, this must be your input errors. BAGEL is used by ~100 research groups and well tested.

By the way CAS18,18 is in the realm of impossibility.
