### ISSUE TITLE
XMS-CASPT2 rotation matrix

### ISSUE THREAD

**Issue by oferfi** [nubakery/bagel#159]
hello and greetings,
I would like to know how to properly read the "XMS-CASPT2 rotation matrix" in order to match between the ci vectors at the CASSCF part and the XMS-CASPT2 energies.
I guess that if values are approaching 1 on the diagonal then "ci vector, state   1" will match with the state 1 XMS energy. basically means no rotation. right?

but what when i get e.g. 0.95 on entry (3,2)? [ i.e. column row 3 column 2 ]

Ofer.

**Comment by shiozaki** [comment]
Hi Ofer,
> when i get e.g. 0.95 on entry (3,2)? [ i.e. column row 3 column 2 ]
It basically means that the states are reordered, but they are not rotated. If you have more questions, send me an email directly at shiozaki.toru@gmail.com. I will close the issue.
Best,
Toru

**Comment by oferfi** [comment]
hello Toru and thank you for your input.
I understand that the rotation matrix tells me how the states are reordered
after the CASSCF level.

my question regards how to match between the "ci vectors" and the energetic
ordering of the states at the XMS level.

best,
Ofer.

**Comment by shiozaki** [comment]
It follows from the theory:
c^{XMS_I} = \sum_R c_R C_{RI}

If you want to print out the CI vector, make the change (insertion of "new_ciwfn->civectors()->print();") below in src/smith/spinfreebase.cc
```
--- a/src/smith/spinfreebase.cc
+++ b/src/smith/spinfreebase.cc
@@ -156,6 +156,7 @@ void SpinFreeMethod<double>::rotate_xms() {
 
   // construct Reference
   shared_ptr<const CIWfn> new_ciwfn = rotate_ciwfn(info_->ciwfn(), fmn);
+  new_ciwfn->civectors()->print();
   auto new_ref = make_shared<Reference>(info_->geom(), make_shared<Coeff>(*info_->coeff()), info_->nclosed(), info_->nact(),
                                         info_->nvirt() + info_->nfrozenvirt(), info_->ref()->energy(), info_->ref()->rdm1(), info_->ref()->rdm2(),
                                         info_->ref()->rdm1_av(), info_->ref()->rdm2_av(), new_ciwfn);
```

**Comment by oferfi** [comment]
thank you for your reply

**Comment by nagb** [comment]
Is there a way to also print out the ci coefficients after the (X)MS-CASPT2 rotation matrix ?

**Comment by shiozaki** [comment]
It appears to me that it's already printed out. Please double check the output.
https://github.com/qsimulate-open/bagel/blob/master/src/smith/spinfreebase.cc#L160

**Comment by shiozaki** [comment]
Ah maybe this was not included in the previous release. Please change the code as in the above comment if you are using the released version.

**Comment by nagb** [comment]
Maybe I'm confused but it seems to me that that is the XMS-CASSCF rotation matrix because it comes before the perturbative step. Then after the single state energies come out, the MS-CASPT2 rotation matrix is printed and XMS-CASPT2 rotation matrix afterwards. It should be this last one that should be equal to the rotation matrix of XMS-CASSCF*MS-CASPT2 correct?
The CI coefficients are printed for XMS-CASSCF step but not for XMS-CASPT2.
