### ISSUE TITLE
Weight for each electronic state in CASSCF calculation

### ISSUE THREAD

**Issue by Jyotirmoyray** [nubakery/bagel#163]

**Comment by Jyotirmoyray** [comment]
Hello, 
     Is it possible to assign weight for individual electronic state in CASSCF calculation in BAGEL ?

**Comment by shiozaki** [comment]
In light of quasi-degenerate perturbation theory, the weight should be equal to all roots; therefore, BAGEL does not allow the weight to be changed. If you exactly know what you are doing, you could edit the following line in src/ci/fci/fci.cc
```
 69   weight_ = vector<double>(nstate_, 1.0/static_cast<double>(nstate_));
```
