### ISSUE TITLE
MECI search input example

### ISSUE THREAD

**Issue by Jyotirmoyray** [nubakery/bagel#164]
Hello, 
    In the BAGEL user manual I didnot find any example input file for conical intersection search. Can you please provide an example file for the MECI search calculation and its corresponding output file ?

**Comment by shiozaki** [comment]
see test/ch2_sto3g_meci_opt.json for the basic input structure. All of the options are tabulated on the online manual. The BAGEL's default threshold is pretty tight for MECI search, so you may be ok with looser threshold. @jwpk1201 anything to add?

**Comment by Jyotirmoyray** [comment]
Thank you for your reply sir. I found the test file. I have one more question. If I use <"molden":true> option for the geometry optimization then the program does not generate molden files for each geometry step. Can you say something about it ?

**Comment by shiozaki** [comment]
The geometry is written in the opt.log file if you want to restart from one of the structures. I will close this issue.

**Comment by jwpk1201** [comment]
Hi Toru,
Nothing to add!
