### ISSUE TITLE
Iridium df_basis

### ISSUE THREAD

**Issue by yapolyak** [nubakery/bagel#165]
I am sorry in advance if the question is naive, but I am trying to run calculations on an Iridium complex, and it seems that while there are three basis files for Iridium (ano-rcc, complete and ecp60mdf), there are no density fitting basis files. Hence the job fails, complaining about the df_basis. Is there a way to run calculations with Iridium?

Many thanks!

Iakov

**Comment by shiozaki** [comment]
Hi Iakov,

The basis set for heavy atoms are indeed a bit of a problem. Perhaps you could use ano-rcc for orbital basis, and uncontracted ano-rcc for df_basis. The basis set files (in src/basis/*.json) are straightforward to construct, and the absolute path to the created file can be used in the input. There is a utility that allows you to uncontract a basis in the repository (see below), so it may help.

Toru

PS: ECP basis has not been used frequently with BAGEL, so I recommend not to use it unless you know what you are doing.

https://github.com/nubakery/bagel/blob/master/src/basis/source/uncontract.py

**Comment by yapolyak** [comment]
Hi Toru,

Thank you very much for your prompt response!

I will follow your advice and will try to use the ano-rcc basis.

Best wishes,

Iakov
