### ISSUE TITLE
segmentation fault when restart_cas is turned on in zcasscf

### ISSUE THREAD

**Issue by xubwa** [nubakery/bagel#170]
I am running a pretty time-consuming zcasscf calculation so I turned on the restart_cas option, and it starts to throw me segmentation fault after the first iteration. If you want to reproduce it, you can simply set restart_cas to true on the hf_tzvpp_zcasscf.json in the test folder of bagel and I am able to reproduce it on the most up-to-date commit.

I dig into the code a little bit and looked at the difference between the normally working restart_cas in nonrelativistic casscf. I think the potential problem might be that. In the zcasscf code, the reference is generated by [https://github.com/nubakery/bagel/blob/0c750f0b44285394304cd80b441e3f288150d4c2/src/multi/zcasscf/zcassecond_compute.cc#L190](url) while in the nonrelativistic casscf code, it is generated by calling the constructor of reference wfn directly.[https://github.com/nubakery/bagel/blob/0c750f0b44285394304cd80b441e3f288150d4c2/src/multi/casscf/cassecond.cc#L141](url) And in the conv_to_ref function, there are multiple lines setting eig_, eigB_, occup_, occupB_ after the constructor of the reference. My guess is that this is how this problem is caused. I tried to use the constructor directly as what was done in the nonrelativistic casscf, it compiles and runs and produces reference at every step, but when I tried to load the reference, it is producing results way different from the result of that step of casscf calculation. Could you please check if this problem is really a bagel issue or it's just I'm doing anything wrong?

**Comment by shiozaki** [comment]
Thanks for reporting this, must be fixed by 364da0c7cc97f2a77b0f96a2db2dbff8ed934257
