### ISSUE TITLE
single state CASSCF dipole moment

### ISSUE THREAD

**Issue by moritzH7** [nubakery/bagel#171]
To my understanding, there currently seems to be no way of calculating the dipole moment in a CASSCF calculation containing only a single state, as the z-casscf calculations do not need to be solved in the "forces" section of the algorithm. Is there any way to obtain the dipole moment in this case apart from calculating a second state in the SA-CASSCF calculation?

thanks

**Comment by shiozaki** [comment]
To clarify: Are you asking to calculate dipole moment in CASSCF with one state (i.e., no state averaging)?

It reads like that, but I don't quite understand what you meant by "apart from calculating a second state in the SA-CASSCF calculation?"

**Comment by shiozaki** [comment]
I mistyped but here is the change assuming it is the case: d543b80612bcf18ea3c854fbd3d8778ad3143c71

**Comment by moritzH7** [comment]
Yes, this is exactly what I meant. One single state in casscf. Thank you very much for the fast reply and change in the code
