### ISSUE TITLE
How to calculate needful amount of  RAM for calculations.

### ISSUE THREAD

**Issue by AndreyShtyrov** [nubakery/bagel#173]
1) I perform nacme and gradient CASSCF(10,10) calculations of systems near by 216 electrons with 538 basis functions. It fail often with error "...Detected 1 oom-kill event(s)...". If i allocate more memory it will solve problem for particular cases. But it would be better if i know estimated ratio between amount of tasks and memory or how it can be calculated.
For example calculation for previous system of con. inter. fail on gradient calculation 
most likely on nacme. With this setup 4 mpi task 1 thread on task (for bagel and mkl) and 26gb ram.

2) Does bagel use disk to save temporary information? If if do where does it save?

**Comment by shiozaki** [comment]
1. The memory requirement for AO integrals are printer at the beginning. This is the requirement for distributed memory. Each MPI process occupies that divided by the number of MPI processes. The total amount of memory required is larger than that, but not by much.

2. No, bagel is designed for parallel hardware and has no disk interface. It won’t be made in the future either.

**Comment by shiozaki** [comment]
I will close this. @jwpk1201 Jae Woo, if you have comments about the memory requirement specifically in NACME, please chime in.
