### ISSUE TITLE
Open MPI is not recommended ?

### ISSUE THREAD

**Issue by miroi** [nubakery/bagel#175]
Hi,

on https://nubakery.org/quickstart/installation_guide.html#build-bagel you claim "--with-mpi=value turns on MPI, where “value” can be “mvapich”, “intel”, or “openmpi”. However, Open MPI is not recommended."

So, the free-of-charge alternative is mvapich, which the user can install himself. Right so ?

**Comment by shiozaki** [comment]
Both mvapich and Intel MPI are free.
