### ISSUE TITLE
Problem with CASPT2 calculations

### ISSUE THREAD

**Issue by AndreyShtyrov** [nubakery/bagel#177]
I have try to make CASPT2(10,10) energy calculation for system consisted from 216 electrons with 538 basis functions. It fail with error 
"BAGEL:19756 terminated with signal 7 at PC=2ac4539a9897 SP=7ffdd46bcc70.  Backtrace:
srun: error: node456: task 0: Bus error
srun: Terminating job step 2074275.0"
But i have give enough memory.

**Comment by shiozaki** [comment]
The bus error is coming from the runtime (srun), so I cannot tell what the cause is. CAS(10,10) with 216 electrons/538 basis functions are routinely done, so I don't expect that's a BAGEL issue. Reopen if you find some evidence otherwise.
