### ISSUE TITLE
Problem with natural occupation number in zcasscf

### ISSUE THREAD

**Issue by xubwa** [nubakery/bagel#179]
Hello,
I noticed there might be a minor problem in the natural occupation number in zcasscf. As I was doing a calculation on Bi2 with active space of (10e,8o) which corresponds to 16 spin orbitals, the natural occupation number is:
Orbital 0 : 0.9999
   Orbital 1 : 0.9991
   Orbital 2 : 0.8439
   Orbital 3 : 0.8097
   Orbital 4 : 0.7113
   Orbital 5 : 0.6372
   Orbital 6 : 0.0006
   Orbital 7 : 0.0003
   Orbital 8 : 0.0001
   Orbital 9 : 0.0009
   Orbital 10 : 0.1561
   Orbital 11 : 0.1903
   Orbital 12 : 0.2887
   Orbital 13 : 0.3628
   Orbital 14 : 0.9994
   Orbital 15 : 0.9997
The sum of all these values is 7.991, which is not equal to number of all electrons. Orbital 8-15 in my understanding should be the related beta orbitals, and their occupation number takes the value of (1-occupation number of related alpha orbital), I think there is simply a minor typo or minor problem in the code.
Best,
Xubo

**Comment by shiozaki** [comment]
Sorry it seems printing problem, just discard 8-15. Their occupation number
is exactly the same as alpha. Orbital 8 = orbital 0 etc.

Toru

**Comment by xubwa** [comment]
I understand that, I just think it seems easy to fix by a line or two, I can also commit but since I'm not sure how does contributing to bagel works, so I'll just leave that to you guys.
Best,
Xubo

**Comment by shiozaki** [comment]
Sure I will take a look when I get some time to spare.
