### ISSUE TITLE
CASSCF and CASPT2 NAC's

### ISSUE THREAD

**Issue by DanielCAValente** [nubakery/bagel#181]
Dear developers and users,
    I have compiled Bagel recently (specifications below) and I noticed a sign inversion in CASPT2 and CASSCF NAC's when compared to the provided test set (test_force.cc). NAC's absolute values and other tests that calculates gradients and MECI geometries, however, seem correct. Below is the CASSCF test results (lif_svp_cas_nacme.out). CASPT2 results are also attached and show a similar sign inversion. 

This is the output calculated:

  * Nuclear energy gradient

    o Atom   0
        x         -0.0000000000
        y         -0.0000000000
        z         -0.2075314771
    o Atom   1
        x          0.0000000000
        y          0.0000000000
        z          0.1243973553

This is in test_force.cc:

  std::vector<double> out(6);
  out[2] =  0.2075313638;
  out[5] =  0.1243972419;
  return out;

  Runing a similar calculation in openmolcas returns the following NAC:

 ---------------------------------------------------------
                     X             Y             Z
 ---------------------------------------------------------
  LI1               0.00000000    0.00000000    0.20889617
  F2               -0.00000000   -0.00000000   -0.12498118
 ---------------------------------------------------------
  My interest lies in nonadiabatic dynamics and the sign does seem to matter. Could this be a compilation error? Below are the options I used in compilation:

Boost - version 1.69
g++/gcc => version 4.8.5
Intel MPI and MKL => version 2019
../configure  --prefix=$PREFIX --enable-mkl --with-boost=$BOOST_ROOT --with-mpi=intel 

    Best regards and thanks,
    Daniel.
[lif_svp_cas_nacme.txt](https://github.com/nubakery/bagel/files/3626618/lif_svp_cas_nacme.txt)
[lif_svp_xmscaspt2_nacme.txt](https://github.com/nubakery/bagel/files/3626646/lif_svp_xmscaspt2_nacme.txt)

**Comment by jwpk1201** [comment]
Hi Daniel,

It is correct behavior, as the signs of the derivative couplings can flip depending on the signs of the wave functions. The correct values are either "-0.2075314771 / 0.1243973553" or "0.2075314771 / -0.1243973553", strongly depending on the initial guess for the orbitals.

Sincerely,
Jae Woo

**Comment by shiozaki** [comment]
That’s a good point, Jae Woo. I’ll close this issue.
