### ISSUE TITLE
Constrained Optimization with BAGEL

### ISSUE THREAD

**Issue by moabe755** [nubakery/bagel#185]
Dear all,

I want to do some excited-state constrained optimizations along a dihedral angle (i.e. excited-state relaxed PE scan) at CASSCF level for several molecular structures. Since I have so many constrained optimizations, I would prefer to use BAGEL to speed up my calculations. I checked the manual of BAGEL, but I could not find how to constrain a coordinate. I wonder whether it is at all possible to perform constrained optimization with BAGEL and if yes how to introduce the constraint(s) to the input file.

Thank you so much.

**Comment by shiozaki** [comment]
Oh sorry I didn't notice this. Unfortunately, BAGEL's optimizer does not support constraints as of now. One may use external optimizers by parsing the forces computed by BAGEL. In this case, save_ref and  load_ref may be useful for picking up a coefficient matrix from the previous geometry step.
