### ISSUE TITLE
ECP issues (Zn, Br)

### ISSUE THREAD

**Issue by yapolyak** [nubakery/bagel#189]
Dear Toru,

I remember you've been mentioning that one should be very careful with using ECP in Bagel. I've however been trying recently to make it work for Br, and while testing, realised that Bagel crashes for me even if I use an ECP/element that Bagel has in its basis set library. The input below for Zn using LANL2DZ segfaults (while for Cu it runs fine). Similarly it crashes for Br when I put the LANL2DZ ECP from basissetexchange.org into Bagel format. Is it possible that the problem is coming from the integrals code and one may try to use libint instead?

Many thanks!

Iakov

--------

{ "bagel" : [

{
  "title" : "molecule",
  "basis" : "lanl2dz-ecp",
  "df_basis" : "svp-jkfit",
  "angstrom" : "true",
  "geometry" : [
    { "atom" : "Zn",  "xyz" : [  0.000000,      0.000000,      0.000000]}
  ]
},

{
  "title" : "hf",
  "charge" : "0"
}

]}

**Comment by shiozaki** [comment]
Sorry but I don't think the ECP code is of production level. And I don't have a bandwidth to fix it now unless someone jumps on it.

**Comment by yapolyak** [comment]
Understood, thank you for your prompt answer!
