### ISSUE TITLE
Feature request: Optimization with constraints

### ISSUE THREAD

**Issue by Alexandr-Zaykov** [nubakery/bagel#190]
Dear BAGEL bakers,

I thoroughly enjoy all the features of BAGEL especially geometry optimizations using CASPT2 gradients, but I wanted to ask whether it would be possible to add a feature that would be widely useful for calculating surfaces - the optimization constraints. Or have I missed it in the manual? Or do you recommend any outside optimizer?
Cheers,

Alexandr

**Comment by shiozaki** [comment]
Sorry for a late reply. I don't think this will be implemented in a foreseeable future. You could export the forces you are getting from BAGEL and use an external optimizer. For instance, it is rather trivial to hack GEOMETric (which has a constrained optimization) to make it work with BAGEL.
