### ISSUE TITLE
CI space accountancy

### ISSUE THREAD

**Issue by nagb** [nubakery/bagel#202]
Hello,

I'm trying to run a CAS(3,3) for all doublets in that space. 

In theory the program should allow me to perform a state average of 8 states as indeed it states on the output: 

  o size of the space 
      determinant space:  9
      spin-adapted space: 8

but for some reason it only allows me to go up to 6 states.  If I go any higher I get the error message: 

"generate_guess produced an invalid determinant.  Check the number of states being requested."

I've managed to track down the source of this message in the code as originating from src/ci/fci/fci.cc. If I understood the programming correctly it evaluates the alpha and beta spins rather than the total number of possible states.

How can this be corrected do you think?

Regards,
Nuno

**Comment by shiozaki** [comment]
If you use
```
"nguess" : 100,
```
(or whatever large number) in the CASSCF block, you could work around the problem. The fundamental fix will take time and won't happen in the near future.

**Comment by nagb** [comment]
Thanks, it worked!

Would you please give that tip in the error message at least? That will warn future users.
