### ISSUE TITLE
XMS-CASPT2 rotation matrix

### ISSUE THREAD

**Issue by panwangzhou** [nubakery/bagel#203]
Dear all，

I performed a xms-caspt2 calculation after sa4-cassf(8,7)/cc-pvdz calcultion, the last of the output file are as following. It seems that the roots 1 and 3 are reordered in the xms-caspt2 calculations (from the results of ++ Extended multi-state CASPT2 (XMS-CASPT2) rotation matrix ++ and others). However, in the last, the diagonal elements of “XMS-CASPT2 rotation matrix” are close to 1. So I'm wondering whether the order of roots  1 and 3 have changed? Thank you.

  ++ State-averaged Fock matrix over basis states ++

                         0                   1                   2                   3
     0       -3.4744508074        0.0000017067       -0.0577317077        0.0551148585
     1        0.0000017067       -3.1169536947        0.0000307948        0.0000038097
     2       -0.0577317077        0.0000307948       -3.1785495451        0.0310042002
     3        0.0551148585        0.0000038097        0.0310042002       -3.2262741047

  ++ Extended multi-state CASPT2 (XMS-CASPT2) rotation matrix ++

                         0                   1                   2                   3
     0       -0.9570651261        0.2678980481        0.1107112227        0.0000735704
     1        0.0000177471        0.0000530833        0.0006894931       -0.9999997607
     2       -0.1935692794       -0.3063568904       -0.9320278704       -0.0006623247
     3        0.2157713562        0.9134418913       -0.3450602826       -0.0001855989

  ++ Reference energies in XMS basis ++

                         0                   1                   2                   3
     0     -799.6834523985        0.0457842614        0.0155570858        0.0000113816
     1        0.0457842614     -799.5297078916       -0.0116046197       -0.0000043375
     2        0.0155570858       -0.0116046197     -799.5355007170        0.0000327005
     3        0.0000113816       -0.0000043375        0.0000327005     -799.5834205354

........

       - CASPT2 energy evaluation                129.24

    * CASPT2 energy : state  0     -802.1270392361
        w/o shift correction       -801.9805316928
        reference weight              0.5771880119

    * CASPT2 energy : state  1     -802.0059888028
        w/o shift correction       -801.8524883647
        reference weight              0.5657701615

    * CASPT2 energy : state  2     -802.0144779318
        w/o shift correction       -801.8576241755
        reference weight              0.5604536775

    * CASPT2 energy : state  3     -802.0248322065
        w/o shift correction       -801.8768711526
        reference weight              0.5747769692

    * MS-CASPT2 Heff
           -802.1270392361        0.0315086256        0.0065097986        0.0000101789
              0.0315086256     -802.0059888028       -0.0020221027        0.0000018167
              0.0065097986       -0.0020221027     -802.0144779318        0.0000276356
              0.0000101789        0.0000018167        0.0000276356     -802.0248322065

    * MS-CASPT2 rotation matrix
             -0.9697586938       -0.0001216273       -0.0609215809        0.2363400559
              0.2374829410       -0.0001749020       -0.0121520722        0.9713156795
              0.0563020731       -0.0026266651       -0.9980651107       -0.0262528456
              0.0000714740        0.9999965276       -0.0026311271        0.0001296735

    * XMS-CASPT2 rotation matrix
              0.9979767195       -0.0001476818       -0.0554467982        0.0311142742
             -0.0000372581       -0.9999981109        0.0019412412       -0.0000920196
              0.0624858076        0.0018629284        0.9457416599       -0.3188491275
             -0.0117469043        0.0005347530        0.3201477736        0.9472946360

    * MS-CASPT2 energy : state  0     -802.1351332878
    * MS-CASPT2 energy : state  1     -802.0248322807
    * MS-CASPT2 energy : state  2     -802.0141051232
    * MS-CASPT2 energy : state  3     -801.9982674856

**Comment by shiozaki** [comment]
The XMS-CASPT2 rotation matrix is a product of the XMS rotation matrix and the MS-CASPT2 rotation matrix. In this example, the CASSCF states and XMS-CASPT2 states are in the same order. See the original XMS-CASPT2 paper for details.
