### ISSUE TITLE
Optimization and clean up in DistRAS

### ISSUE THREAD

**Issue by smparker** [nubakery/bagel#26]
DistRAS still needs to incorporate some recent changes that were put into the serial version of RAS.
  - form reduced lists and reduced C' before sparse matrix multiplies (see commit ce16cd6)
  - only form sparse matrices as needed (see commit 661d1dd)
  - clean up communication with ireduce_scatter

**Comment by shiozaki** [comment]
I disabled DistRAS for the time being.
