### ISSUE TITLE
Refactoring complex DF objects

### ISSUE THREAD

**Issue by RDReynolds** [nubakery/bagel#50]
Currently, complex density-fitted integral 3-tensors are derived from standard DF objects and have analogous member functions with different names.  This works but is not very elegant; in principle the interfaces for real and complex DF objects should be identical.  Introducing polymorphic behavior is not straightforward due to differences in arguments and return type for some functions.  

Not sure at this point what is the best solution…

**Comment by shiozaki** [comment]
checking in. If that is the only problem, you could define the following (and others) in the base:
```
using MatType = typename std::conditional<std::is_same<DataType,double>::value,Matrix,ZMatrix>::type;
```
You should be able to merge them.

**Comment by RDReynolds** [comment]
We need to have ComplexDFDist be derived from DFDist, though.  (Otherwise we need a separate Geometry class or two sets of integrals in Geometry - which caused many headaches in the past.)   Currently this is achieved by having the same basic structure, but with twice as many DFBlocks to represent the real and imaginary parts.  No templating is used.  

I don't see how having a shared base class instead will work.  If we have the needed functions defined in derived classes, then we would need to do pointer casts in order to use them with or without magnetic fields.  If we have the functions in the base, then it needs to be a templated base class, and we can't store either version in one member of Geometry.  

Over time, I've come to think the current implementation is adequate.  It works, and there's not too much redundancy in the implementation since the functions of DFBlock are still used.  (complexdf.cc is little more than a collection of calls to DFBlock functions and zgemm3m-type multiplications.)  There might still be a better way to merge DFDistInts and ComplexDFDistInts.
