### ISSUE TITLE
Scalapack diagonalization sometimes hangs

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#52]
In some cases ScaLapack abruptly hangs during the diagonalization (especially for small systems when the number of processes is large). Need to be fixed.

**Comment by shiozaki** [comment]
We need to check if this still persists.

**Comment by shiozaki** [comment]
@jwpk1201 Jae Woo, have you noticed this recently? I don't think we've changed anything, but I don't recall seeing this recently.

**Comment by jwpk1201** [comment]
No, I haven't. Maybe because I did not use many processes for small systems, like, two atoms.

**Comment by shiozaki** [comment]
OK, let me close this for now. If you observe this, please reopen.
