### ISSUE TITLE
Various coefficients in relativistic CASSCF

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#56]
This is a huge mess at the moment.

Ryan - I know it's not your fault, but can you introduce appropriate coefficient classes so that transformation between each format is understandable. The transformation should be done in the constructors of these classes, and there should be a function that returns shared_ptr\<Kramers\<2,ZMatrix\>\>, for instance.

**Comment by shiozaki** [comment]
Clarification: I think each format should have a corresponding class. Currently it's too dangerous - for instance, if one looks at RelReference, it is impossible to know what kind of coefficients are stored there.

**Comment by RDReynolds** [comment]
I have created a pull request containing the requested changes.  Three classes were created to deal with this issue (plus a shared base class).  

RelCoeff_Striped is stored in RelReference and used when generating an initial guess.  RelCoeff_Block is used for most of the internal work in ZFCI and ZCASSCF.  RelCoeff_Kramers helps to interface with the quaternion diagonalization routine.
