### ISSUE TITLE
Const-correctness of CASSCF and ZCASSCF functions

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#58]
There are many functions that implicitly modify coeff_ and occup_ in CASSCF and ZCASSCF. In order to make them transparent, I want these functions to be const (returning new coefficients etc), and the driver functions explicitly assign these members. Thanks Ryan in advance.

**Comment by RDReynolds** [comment]
The following functions have been made const.  (A few were also moved into RelCoeff.)   

ZCASSCF::init_kramers_coeff()
ZCASSCF::generate_mvo()
ZCASSCF::make_natural_orbitals()
ZCASSCF::active_fock();
ZCASBFGS::optimize_subspace_rotations();
FCI::detseeds();
ZFCI::detseeds();

I also inlined CASSCF::form_natural_orbs() (which is very short) for the same reason.
