### ISSUE TITLE
linear dependent basis in Rel-CASSCF

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#61]
per discussion, we are not sure if relativistic CASSCF is properly working with basis functions that have linear dependency. There is probably a bug.

**Comment by shiozaki** [comment]
@RDReynolds  What's the status?

**Comment by RDReynolds** [comment]
I think I did some work on this a while back, but currently it is broken.  Working on a fix...

**Comment by RDReynolds** [comment]
This issue is now fixed on Gauge branch, and may be closed once the changes are merged to master.

**Comment by shiozaki** [comment]
Fixed by 99a893850ebd1be47f6c84e7c926a11dfb56cb44
