### ISSUE TITLE
[patch] Missing testcase/examples for CASPT2/SMITH methods

### ISSUE THREAD

**Issue by mbanck** [nubakery/bagel#64]
The testsuite does not cover CASPT2 (or any other SMITH3-based method). The following `lif_svp_caspt2.json` (adopted from `lif_svp_cas22.json`) works for me:

```
{ "bagel" : [

{
  "title" : "molecule",
  "symmetry" : "C1",
  "basis" : "svp",
  "df_basis" : "qzvpp-jkfit",
  "angstrom" : false,
  "geometry" : [
    {"atom" : "Li",  "xyz" : [  -0.000000,     -0.000000,     10.000000]},
    {"atom" : "F",   "xyz" : [  -0.000000,     -0.000000,      0.000000]}
  ]
},

{
  "title" : "casscf",
  "nact" : 0,
  "nact_cas" : 2,
  "nclosed" : 5
},

{
  "title" : "smith",
  "method" : "caspt2"
}

]}
```

Is this the correct way to run a CASPT2 single-point computation?

It yields the following energies on my laptop:

```
     13       -106.61640071          0.00000001           0.00

    * SCF iteration converged.
[...]
      2  0 *    -106.70563743     2.87e-16      0.00
[...]
    * CASPT2 energy :      -106.8522335111
```

And I get basically the same values from MOLPRO-2012.1:

```
        DF-RS2          DF-MULTI        DF-HF
   -106.85223351   -106.70563743   -106.61640068
```

So far, I have not managed to figure out a valid input for CASPT2 geometry optimizations, but I guess those should be possible as well?

**Comment by shiozaki** [comment]
It's intentional - The generated code includes unpublished results, so please do not do it. Thanks.

**Comment by mbanck** [comment]
> It's intentional - The generated code includes unpublished results, so please do not do it. Thanks.

I'm wondering, is this still the case now that 10.1021/acs.jctc.5b00754 ("Relativistic Internally Contracted Multireference Electron Correlation Methods") is out?

**Comment by shiozaki** [comment]
Yes. That's why it's disabled unless users specify to compile it.
