### ISSUE TITLE
COPYING/README says GPL3+ while copyright headers in most files say LGPL3+

### ISSUE THREAD

**Issue by mbanck** [nubakery/bagel#65]
While doing a copyright review we noticed that all dedicated files in BAGEL have a LGPL license header. The only GPL files are the imported src/alglib ones apparently (plus LGPL2+/BSD for the MPFR routines in src/integral).

This is not really an issue per se, but I thought I'd bring it up because COPYING and README seem to imply a different intent than what the code copyright really is (it is my understanding that a top-level COPYING pertains to at most files which have no explicit copyright, but explicit copyrights in files take precedence).

**Comment by shiozaki** [comment]
Many thanks. It's a shame nobody has noticed this for this long. I or somebody must have used some wrong script to insert the header. What all the copyright holders have agreed was GPL (not LGPL).

In the end, I personally don't really care (so perhaps you can download this now and use it somewhere :-)), but I will change the headers later today.
