### ISSUE TITLE
Replace GA with MPI-3 RMA

### ISSUE THREAD

**Issue by jeffhammond** [nubakery/bagel#69]
Are you considering using GA in BAGEL?  https://github.com/nubakery/bagel/blob/master/src/util/parallel/mpi_interface.cc#L89 suggests so.

You might want to reconsider and use MPI-3 RMA directly instead.  I can give you a very long list of reasons if you're interested.

**Comment by shiozaki** [comment]
Yes, it is currently used in a code-generator-based code (but GA calls are localized in https://github.com/nubakery/bagel/blob/master/src/smith/storage.cc).

You are probably right. I am only using ARMCI-type operations with 1dim arrays and GA is an overkill. I thought of calling ARMCI directly but I wasn't sure about the interface (and, well, I intended to use your ARMCI-MPI3). In addition, it is always good to avoid dependency to other libraries wherever possible.

I'd be interested in your reasoning, so please write to me via email.

**Comment by jeffhammond** [comment]
Thanks for the pointer to code. I can rewrite that to use MPI-3 in an hour or so.  Will send PR ASAP.

Since you are not opposed to the idea, I'll summarize the ARMCI->MPI RMA argument here:
* MPI-3 RMA is reliably implemented in MPICH 3.2+, Intel MPI 5.1+, Cray MPI 7.2+ and MVAPICH2 (not sure about version).  Other than a bug in `MPI_Fetch_and_op` in MPICH 3.1 that went downstream, it's been reliable since MPICH 3.0 (and derivative) days. Open-MPI support for MPI-3 RMA is almost there.  https://travis-ci.org/jeffhammond/armci-mpi reveals the known issues, which are specific to when noncontiguous datatypes are used (you clearly don't need these) and are easy enough to work around (ARMCI-MPI can do this, and does so when Open-MPI is used).
* GA/ARMCI is defaulting to MPI-based conduits (not RMA-based but using Send-Recv), because of the inherent reliability of MPI and unreliability of their DMAPP and TCP/IP ports, among others.  The best ARMCI port is for Mellanox InfiniBand (it does not work on Intel InfiniBand as far as I know) and even that one crashes incessantly if one runs large-memory NWChem jobs.
* The performance issues associated with MPI RMA can be addressed with Casper (see [paper](http://www.mcs.anl.gov/publication/casper-asynchronous-progress-model-mpi-rma-many-core-architectures) and [code](http://git.mpich.org/soft/dev/casper.git/)). Casper works with an MPI-3 RMA implementation - including proprietary ones like Cray MPI and Intel MPI - via `LD_PRELOAD` and PMPI interposition, hence is completely transparent to the application.
* ARMCI sets its own signal handlers, uses its own memory allocator and does other things that make it harder to debug application issues.  Furthermore, there are a myriad of MPI-based performance and correctness tools out there, and while some of them may not yet support RMA, the changes of them doing so is much greater than supporting ARMCI.
* While the MPI-3 specification makes RMA seem rather complicated, the semantics are quite good once you understand them, and the quantum chemist in the MPI Forum is happy to answer any questions you may have ;-)

My PR will be comment-heavy with relevant technical details.

**Comment by shiozaki** [comment]
Jeff, I learned from your stab and implemented what I think is right. Please checkout 9fdfe8ccc365e8dbcdfa3001c3056eb1ab3d480f (or the current master branch).

There is one more place (distributed FCI) in which I have to replace GA with this - will be done soon.

**Comment by jeffhammond** [comment]
Regarding testing this before closing, can you tell me which test or example input to run to validate it?  I will try to run on NERSC Cray machines.  It is good to validate on more than one implementation.  I can test on Intel MPI, MVAPICH and Open-MPI at some point since I need to do ARMCI-MPI QA against them anyways.

**Comment by shiozaki** [comment]
Sure. Note that this example is good for 4 MPI processes or so (at the moment the code could die silently with too a large number of MPI processes).
```
cd BAGEL/obj/src
mpirun -machinefile hosts.txt -n 4 ./BAGEL cutest.json
```
cutest.json
```
{ "bagel" : [ 

{
  "title" : "molecule",
  "symmetry" : "C1",
  "basis" : "cc-pvdz",
  "df_basis" : "svp",
  "angstrom" : "false",
  "geometry" : [ 
  { "atom" : "Cu", "xyz" : [ 0.000000000,   0.000000000,   1.201383939 ]}, 
  { "atom" : "O" , "xyz" : [ 0.000000000,   1.290968296,   4.531837273 ]}, 
  { "atom" : "O" , "xyz" : [ 0.000000000,  -1.290968296,   4.531837273 ]}, 
  { "atom" : "C" , "xyz" : [ 0.000000000,   2.341068321,  -3.655648745 ]}, 
  { "atom" : "C" , "xyz" : [ 0.000000000,  -2.341068321,  -3.655648745 ]}, 
  { "atom" : "C" , "xyz" : [ 0.000000000,   0.000000000,  -4.904366545 ]}, 
  { "atom" : "N" , "xyz" : [ 0.000000000,  -2.666893011,  -1.162939351 ]}, 
  { "atom" : "N" , "xyz" : [ 0.000000000,   2.666893011,  -1.162939351 ]}, 
  { "atom" : "H" , "xyz" : [ 0.000000000,   0.000000000,  -6.963799531 ]}, 
  { "atom" : "H" , "xyz" : [ 0.000000000,   4.503052965,  -0.570064233 ]}, 
  { "atom" : "H" , "xyz" : [ 0.000000000,  -4.503052965,  -0.570064233 ]}, 
  { "atom" : "H" , "xyz" : [ 0.000000000,   4.052103839,  -4.835249811 ]}, 
  { "atom" : "H" , "xyz" : [ 0.000000000,  -4.052103839,  -4.835249811 ]}
  ]
},

{
  "title" : "hf"
},

{
  "title" : "casscf",
  "algorithm" : "hybrid",
  "maxiter_switch" : 10, 
  "maxiter" : 200,
  "nclosed" : 34, 
  "active" : [17, 20, 31, 32, 34, 39, 40, 42, 56],
  "nact_cas" : 9 
},

{
  "title" : "casscf",
  "algorithm" : "hybrid",
  "maxiter_switch" : 10, 
  "maxiter" : 200,
  "nclosed" : 37, 
  "nact_cas" : 6 
},

{
  "title" : "smith",
  "method" : "caspt2",
  "maxtile" : 10, 
  "thresh" : 1.0e-9,
  "frozen" : true
}

]}
```
The result will be
```
    * freezing 16 orbitals
       - MO integral evaluation                    0.43
    - linear dependency detected:    2 /   72    min eigenvalue:     1.5066e-15    max eigenvalue:     7.1749e-15
    - linear dependency detected:   29 /  216    min eigenvalue:    -5.6600e-15    max eigenvalue:     3.2526e-10
    - linear dependency detected:  146 /  216    min eigenvalue:    -8.1663e-15    max eigenvalue:     8.8968e-15
       - RDM + denominator evaluation              0.52

    * Zeroth order energy : state  0       -5.6636777807

      ---- iteration ----

        0    -1.39049474     0.00006010      1.92
        1    -1.39259460     0.00000629      2.09
        2    -1.39263813     0.00000094      2.03
        3    -1.39263891     0.00000011      2.08
        4    -1.39263892     0.00000001      2.10
        5    -1.39263892     0.00000000      2.14
        6    -1.39263892     0.00000000      2.17

      -------------------

       - CASPT2 energy evaluation                 14.77

    * CASPT2 energy : state  0    -2009.8781279983

    * METHOD: SMITH                               15.78
```
If you want to enjoy more, you could replace "caspt2" with "MRCI".

**Comment by shiozaki** [comment]
The code is working on our cluster just fine. I close this issue - if you find some errors please open another issue.

**Comment by jeffhammond** [comment]
Great.  That's good enough for me for now.

If you see any issues with MPI-3, please let me know.  I have a relatively large cache of all the quirks in various implementations.
