### ISSUE TITLE
DistFCI does not work with MPI_Rget and MPI_Raccumulate

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#70]
See FIXME in https://github.com/nubakery/bagel/blob/master/src/ci/fci/distcivec.cc. The code dies with (using recent IntelMPI)
```
Fatal error in MPI_Raccumulate: Wrong synchronization of RMA calls , error stack:
MPI_Raccumulate(192)..: MPI_Raccumulate(origin_addr=0x6680d70, origin_count=6, MPI_DOUBLE, target_rank=1, target_disp=0, target_count=6, MPI_DOUBLE, MPI_SUM, win=0xa0000004, request=0x7fff32aabf6c) failed
MPIDI_Raccumulate(330): Wrong synchronization of RMA calls 
Fatal error in MPI_Raccumulate: Wrong synchronization of RMA calls , error stack:
MPI_Raccumulate(192)..: MPI_Raccumulate(origin_addr=0x7ca9940, origin_count=6, MPI_DOUBLE, target_rank=0, target_disp=0, target_count=6, MPI_DOUBLE, MPI_SUM, win=0xa0000004, request=0x7fff79d2f40c) failed
MPIDI_Raccumulate(330): Wrong synchronization of RMA calls 
```
The code with MPI_Get and MPI_Accumulate does work, so I'm marking this as enhancement. It must be that I haven't understood something about MPI3-RMA.

Related to #69

**Comment by jeffhammond** [comment]
This is due to the lack of lock epoch stuff I noted in the comment on the commit.  If you want me to work up a patch, please let me know.  I don't think it would be too hard.  The part of your code that is hardest for me is the non-MPI stuff, but you have already taken care of that.

**Comment by shiozaki** [comment]
Thanks - I will work on it and see if I can fix them. Otherwise I will write to you some questions on this thread.

**Comment by jeffhammond** [comment]
I already have a patch for src/smith/storage.cc.  I'll push it in less than 5 minutes.  You are more than welcome to rewrite, of course, but looking at my code may help convey what I meant to say before in a more explicit manner.

**Comment by jeffhammond** [comment]
https://github.com/jeffhammond/bagel/commit/52e7fae109a73cf4c269ea7638ce357fc8f22839

**Comment by shiozaki** [comment]
Cool, I will start from there!

**Comment by jeffhammond** [comment]
Does this mean your code is running correctly with RMA now?  If so, that's awesome.

**Comment by shiozaki** [comment]
It does! Indeed, that's awesome. I'll test a bit more before closing #69.
