### ISSUE TITLE
Some basis sets not in Makefile.am's data_DATA

### ISSUE THREAD

**Issue by mbanck** [nubakery/bagel#74]
The following basis sets in src/basis are not in the corresponding Makefile.am's data_DATA and are thus not installed upon make install:

`6-31g.json aug-cc-pv5z.json aug-cc-pv6z.json complete.json def2-SVP-2c-ecp.json def2-SVP-ecp.json ecp10mdf.json ecp28mdf.json ecp46mdf.json ecp60mdf.json ecp78mdf.json lanl2dz-ecp.json`

I first thought maybe the ECP basis sets weren't supposed to be in stalled, but it looks strange that 3-21G is installed but 6-31G isn't (same for the A{5,6}TZ basis sets), so opening an issue about it for your consideration.

**Comment by shiozaki** [comment]
@haianhle Anh, can you fix this in your spare time? Not too urgent, but has to be done.

Michael, generally speaking "make install" is not very well tested. Note that this is still officially a pre-alpha version. I plan to do the first release in 15 months.

**Comment by mbanck** [comment]
For the record, this is the patch I'm using (could be prettified, of course):

```
--- ./src/basis/Makefile.am.orig        2016-05-08 09:57:34.736825702 +0200
+++ ./src/basis/Makefile.am     2016-05-08 09:58:17.528827637 +0200
@@ -2,4 +2,5 @@
 cc-pv5z-jkfit.json cc-pvdz-jkfit.json cc-pvqz-ri.json cc-pvtz.json sto-3g.json tzvpp.json \
 aug-cc-pvdz.json cc-pv5z-ri.json cc-pvdz-ri.json cc-pvqz.json qzvpp-jkfit.json svp-jkfit.json \
 aug-cc-pvqz.json cc-pv5z.json cc-pvdz.json cc-pvtz-jkfit.json qzvpp.json svp.json \
-ano-rcc.json
+ano-rcc.json \
+6-31g.json aug-cc-pv5z.json aug-cc-pv6z.json complete.json def2-SVP-2c-ecp.json def2-SVP-ecp.json ecp10mdf.json ecp28mdf.json ecp46mdf.json ecp60mdf.json ecp78mdf.json lanl2dz-ecp.json
```
