### ISSUE TITLE
Is there any information on how to use this package?

### ISSUE THREAD

**Issue by Hassenky** [nubakery/bagel#75]
Hi developers,

I am quite interested in analytical gradient optimization at the CASPT2 level. Is there any document showing how to use this package (symmetry, active space, calculation restart, and so on)?

Thanks,

**Comment by shiozaki** [comment]
We are planning on doing the initial release in the summer 2017. The CASPT2 gradients have a few pending publications on the methodologies, so let us focus on them first. If you consider using it for research projects now, please write me an email; I'll let you know how it works.
