### ISSUE TITLE
Internal coordinate

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#78]
In some cases, the internal coordinate is not properly handled. For instance, dihedral angles are not included in H2CO, and the transformation matrix is singular. When it is included, there is in turn another problem. There should be a way to fix this...

**Comment by shiozaki** [comment]
It seems that we should rethink how to reorient molecule (i.e., separating rotation and translation from the geometry optimization...; this matters because we don't update the transformation to the internal coordinate at the moment).

**Comment by shiozaki** [comment]
Duplication of #18

**Comment by shiozaki** [comment]
@jwpk1201 Jae Woo, do you think that this has been resolved by your recent edits?

**Comment by jwpk1201** [comment]
@shiozaki Toru, I actually do not think so (and actually I didn't realize it until I saw this). I did not modify the internal coordinate generation routine in molecule/molecule.cc . I tried to optimize the geometry of H2CO (just for test) with delocalized internals, and experienced same problem (the transformed gradient is too large). When I use the redundant internals, I did not have this problem. I will look through this.

**Comment by shiozaki** [comment]
Thanks. Prioritize your coding for research, but please do in your spare time.

**Comment by shiozaki** [comment]
@jwpk1201 What is the status?

**Comment by jwpk1201** [comment]
This is not solved yet.

**Comment by jwpk1201** [comment]
For triangular molecules (such as formaldehyde), this is solved by adding improper dihedral coordinate.

**Comment by shiozaki** [comment]
I think this also happened on large molecules. Bess, you had an example, right?

On May 25, 2017, at 4:24 PM, Jae Woo Park <notifications@github.com<mailto:notifications@github.com>> wrote:


For triangular molecules (such as formaldehyde), this is solved by adding improper dihedral coordinate.

-

**Comment by shiozaki** [comment]
Will close after merging into master.
