### ISSUE TITLE
1- and 2-particle CASPT2 relaxed density matrices

### ISSUE THREAD

**Issue by cuanto** [nubakery/bagel#79]
Hello,

I would like to know if, it is possible to print the 1-RDM/2-RDM spin free, or at least the 2-RDM spin free for the following methods CASPT2, NEVPT2 or MRCI ? also, it is possible to print the canonical orbitals in molden format for these methods and not natural orbitals ?

I would like to use it for real space integration, for example Bader or Hirshfeld basins, for which I need the canonical orbitals (the program internally build the natural orbitals) and at least the 2-RDM.

Is there any detailed documentation on how to use the code?

Best regards,
Jose

**Comment by shiozaki** [comment]
Hi Jose,

(1) We can compute CASPT2 relaxed density matrices, which are implemented for nuclear gradient theories. Unfortunately we use density fitting for efficiency, and therefore we do not construct 2-particle density matrices explicitly. Modifying code should be easy, so if you opt to do that, I would be happy to help you navigate through the BAGEL program. Basically the relevant code is localized in bagel/src/smith/caspt2grad.cc and caspt2grad_util.cc. The input below would run through these code.

(2) We do not have NEVPT2/MRCI gradients, and therefore, we do not have relaxed density matrices. Note that use of unrelaxed density matrices is strongly discouraged for any property calculations.

(3) I am not sure what you mean by canonical orbitals in this case. Do you mean CASSCF semi-canonical orbitals (which is canonicalized within the closed, active, and virtual subspaces)? If so, it is easy. Apply the following patch.
```
diff --git a/src/multi/casscf/casscf.cc b/src/multi/casscf/casscf.cc
index 06e628c..ee394c5 100644
--- a/src/multi/casscf/casscf.cc
+++ b/src/multi/casscf/casscf.cc
@@ -317,6 +317,11 @@ shared_ptr<const Coeff> CASSCF::semi_canonical_orb() const {
     ofock.diagonalize(eig);
     trans.copy_block(0, 0, nclosed_, nclosed_, ofock);
   }
+  if (nact_) {
+    Matrix afock = acoeff % fock * acoeff;
+    afock.diagonalize(eig);
+    trans.copy_block(nclosed_, nclosed_, nact_, nact_, afock);
+  }
   Matrix vfock = vcoeff % fock * vcoeff;
   vfock.diagonalize(eig);
   trans.copy_block(nocc_, nocc_, nvirt_, nvirt_, vfock);
```
If you do not want to respect subspaces (canonical orbitals of the entire orbital space), however, it is not easy to make it consistent with the CASPT2 calculation.

(4) General documentation will be available by the next summer (we are severely man-power limited, but we are working on it). Currently there is no documentation...

Best,
Toru

PS: simple input to calculate nuclear forces, in which CASPT2 density matrices are evaluted:
```
{ "bagel" : [ 
{
  "title" : "molecule",
  "basis" : "svp",
  "df_basis" : "tzvpp-jkfit",
  "angstrom" : false,
  "geometry" : [ 
    { "atom" : "C",  "xyz" : [   -0.000000,     -0.000000,   -0.160513540] },
    { "atom" : "H",  "xyz" : [   -0.000000,   1.753156740,  0.9563704820] },
    { "atom" : "H",  "xyz" : [   -0.000000,  -1.753156740,   0.956370482] }
  ]
},

{
  "title" : "hf"
},

{
  "title" : "casscf",
  "nact" : 3,
  "algorithm" : "hybrid",
  "maxiter_switch" : 10, 
  "bfgstype" : "alglib",
  "nclosed" : 2 
},

{
  "title" : "force",
  "method" : [ { 
    "title" : "caspt2",
    "smith" : { 
      "method" : "caspt2",
      "frozen" : true,
      "maxtile" : 100,
      "ncore" : 1 
    },  
    "algorithm" : "noopt",
    "nact" : 3,
    "nclosed" : 2 
  } ] 
}
]}
```

**Comment by cuanto** [comment]
Hi Toru, 

First thank you for the great response to my question :-). Yes I was asking about relaxed densities, thanks for clarifying the title.

I was reading the source code, but as a fortran user it is difficult for me, I have never programmed in c++, I would like to program it but I need to read at least a c++ book !!!

Usually I was using pyscf for CASSCF, I think it uses canonicalization on the entire space instead of subspaces, https://github.com/sunqm/pyscf/blob/master/mcscf/casci.py - line 261. But for CASPT2 I am not sure what I should use. I would like to give you a more clear answer, but I am still a student and CASSCF/CASPT2 math details are not easy for me.

Concerning the doc, using grep and searching title keyword is enough for me.

Again thanks for your time and patience and congratulations for the bagel code :-) 

Best regards,
Jose

**Comment by shiozaki** [comment]
Hi Jose,

Great. One more thing to add: BAGEL's CASPT2 can be started from the Molden files generated by other programs (such as pyscf). BAGEL's CASSCF is not bullet proof (e.g., we do not have symmetry yet), so that's also an option.

I'll close this issue, but if you have any questions, please reopen, or send me an email to shiozaki@northwestern.edu.

Best,
Toru
