### ISSUE TITLE
Address not mapped in relativistic MRCI

### ISSUE THREAD

**Issue by jevandezande** [nubakery/bagel#80]
I was recently attempting to create a simple molecule to optimize with relativistic MRCI using an external optimizer (PSI4). I have tried different variants of small molecules, and often get the message:
```
    * Zeroth order energy : state  0       -1.7531177475

      ---- iteration ----

[n029:30787] *** Process received signal ***
[n029:30787] Signal: Segmentation fault (11)
[n029:30787] Signal code: Address not mapped (1)
[n029:30787] Failing at address: 0x10
[n029:30787] [ 0] /lib64/libpthread.so.0(+0xf100)[0x2b3247e1d100]
[n029:30787] [ 1] /opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/bagel-master-u2wax74ze66y6fm67tmmmq65sabkztmm/lib/libbagel_smith.so.0(+0x1e223d4)[0x2b3230b413d4]
[n029:30787] [ 2] /opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/bagel-master-u2wax74ze66y6fm67tmmmq65sabkztmm/lib/libbagel_smith.so.0(_ZN5bagel5SMITH7Tensor_ISt7complexIdEEC1ESt6vectorINS0_10IndexRangeESaIS6_EEbSt13unordered_setImSt4hashImESt8equal_toImESaImEEb+0xb4)[0x2b3230b474c4]
[n029:30787] [ 3] /opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/bagel-master-u2wax74ze66y6fm67tmmmq65sabkztmm/lib/libbagel_smith.so.0(_ZSt11make_sharedIN5bagel5SMITH7Tensor_ISt7complexIdEEEIRSt6vectorINS1_10IndexRangeESaIS7_EEEESt10shared_ptrIT_EDpOT0_+0xf0)[0x2b3233b1d590]
[n029:30787] [ 4] /opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/bagel-master-u2wax74ze66y6fm67tmmmq65sabkztmm/lib/libbagel_smith.so.0(_ZN5bagel5SMITH7RelMRCI7RelMRCI12make_sourceqEbb+0x22e)[0x2b3233fa22ce]
[n029:30787] [ 5] /opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/bagel-master-u2wax74ze66y6fm67tmmmq65sabkztmm/lib/libbagel_smith.so.0(+0x51bcac0)[0x2b3233edbac0]
[n029:30787] [ 6] BAGEL[0x52a49b]
[n029:30787] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2b3249201b15]
[n029:30787] [ 8] BAGEL[0x5296e9]
[n029:30787] *** End of error message ***
```

I have tried with H<sub>2</sub>, H<sub>3</sub>, H<sub>4</sub>, HHe, He<sub>2</sub>, Li<sub>2</sub> only to receive the same error message. I have been using (variations of) the input:

```
{ "bagel" : [ 
{
    "title" : "molecule",
    "symmetry" : "C1",
    "basis" : "svp",
    "df_basis" : "svp-jkfit",
    "angstrom" : true,
    "geometry" : [ 
        {"atom" : "H",  "xyz" : [ 0.0, 0.0, 1.0]},
        {"atom" : "H",  "xyz" : [ 0.0, 0.0, 0.0]}
    ]
},{
    "title" : "zcasscf",
    "algorithm" : "bfgs",
    "state" : [ 1 ],
    "nact_cas" : 2,
    "nclosed" : 0
},{
    "title" : "relsmith",
    "method" : "mrci",
    "ncore" : 0
}
]}
```

This is occasionally related to an unconverged CASSCF (which in my opinion should probably throw an error if it fails to converge in the specified number of iterations), but also happens when the previous computations have converged. I have attempted adding various flags, including `"occ_sort" : true`. Is there any way to get these computations to run properly or are there any other simple test cases I can use? Anything much bigger starts to take a long time to run.

**Comment by shiozaki** [comment]
I am at a conference this week and cannot reproduce by myself, but I wanted to comment that relativistic CASSCF will soon be replaced by a more robust algorithm.

@RDReynolds if you can comment, please do.

**Comment by shiozaki** [comment]
Ah, actually the SMITH code may not work without any closed orbitals. Please try HHe with one closed orbital.

**Comment by jevandezande** [comment]
That seems to fix it. It appears that you need to have some closed orbitals that are not also frozen in the MRCI portion of the computation. Thanks.
