### ISSUE TITLE
CASPT2 gradient test

### ISSUE THREAD

**Issue by stbaruc** [nubakery/bagel#81]
Hello,

I am trying to do a test of CASPT2 gradient using BAGEL and I miss an example in the test section. Could it be included?

Thank you,

Jesús

**Comment by shiozaki** [comment]
Jesús,

Here is a sample input. We will work on the test files later (before the official release scheduled next summer), so let me close the issue.

Note:
"target" is the target state (0 is the ground state). "sssr" is the kind of internal contraction (see the latest JCTC we just published). "shift" is the vertical shift. "ncore" is the number of frozen core orbitals. "nact" is the number of open orbitals in ROHF and "nact_cas" is the number of active orbitals (we will probably rename those keywords in the near future as it is confusing).

Hopefully this helps,
Toru

```
{ "bagel" : [ 

{
  "title" : "molecule",
  "symmetry" : "C1",
  "basis" : "svp",
  "df_basis" : "tzvpp-jkfit",
  "angstrom" : false,
  "geometry" : [ 
    { "atom" : "C",  "xyz" : [   -0.000000,     -0.000000,   -0.160513540] },
    { "atom" : "H",  "xyz" : [   -0.000000,   1.753156740,  0.9563704820] },
    { "atom" : "H",  "xyz" : [   -0.000000,  -1.753156740,   0.956370482] }
  ]
},

{
  "title" : "optimize",
  "target" : 0,
  "method" : [ 
    {   
    "title" : "caspt2",
    "smith" : { 
      "method" : "caspt2",
      "frozen" : true,
      "xms" : true,
      "sssr" : true,
      "shift"  : 0.2,
      "ncore" : 1 
    },  
    "nstate" : 3,
    "nact" : 0,
    "nact_cas" : 3,
    "thresh" : 1.0e-8,
    "nclosed" : 2 
  } ] 
}

]}
```

**Comment by shiozaki** [comment]
PS: if you only want to compute gradients, please replace "optimize" with "force".

**Comment by stbaruc** [comment]
Thank you very much
