### ISSUE TITLE
bug in MS-CASPT2 gradients

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#84]
The commit b720269f235ac12a1aa39316f11ded042de2ed24 broke MS-CASPT2 gradients (but not XMS-CASPT2 gradients). In addition, the XMS-CASPT2 gradients seem too inaccurate.

Under debugging.

**Comment by bessvlai** [comment]
The XMS-CASPT2 analytical gradient code was tested by comparison with two and four point finite difference numerical gradients.  A displacement of 0.001 Bohr was used when computing the numerical gradients. Unless noted, in the tests the MS-MR internal contraction and no vertical shift were used. The following molecules were included: LiF (2 electrons in 2 orbitals, 2 states), LiF (4 electrons in 4 orbitals, 4 states), CH2 (4 electrons in 3 orbitals, 3 states), CH2 (4 electrons in 3 orbitals, 4 states), HF (6 electrons in 4 orbitals, 4 states), H2O (4 electrons in 4 orbitals, 4 states), and acetone (4 electrons in 3 orbitals, 3 states). The analytical gradient agrees with the finite difference to at least five digits for these systems.

LiF (2 electrons in 2 orbitals, 2 states), CH2 (4 electrons in 3 orbitals, 3 states), HF (6 electrons in 4 orbitals, 4 states), H2O (4 electrons in 4 orbitals, 4 states), and acetone (4 electrons in 3 orbitals, 3 states were also used as tests for the MS-CASPT2 gradient. Additionally, for LiF (2 electrons in 2 orbitals, 2 states), the gradients were compared using the SS-SR internal contraction.

**Comment by shiozaki** [comment]
Thanks, I close this now.
