### ISSUE TITLE
optimize: maxiter off by one

### ISSUE THREAD

**Issue by mbanck** [nubakery/bagel#90]
The logic with respect to ```maxiter ```during geometry optimizations in ```opt.cc ``` is:

```
  for (iter_ = 1; iter_ != maxiter_; ++iter_) {
```
If I set ```"maxiter" : 1```, BAGEL unexpectedly (at least to me), did not run any optimization steps; if I set it to 2, it runs one.  I think the logic should be that it runs ```maxiter``` steps, and exits after those if there is no convergence.

**Comment by shiozaki** [comment]
I don't think this is a bug (just a different convention), therefore we close this issue. Note, for instance, if you set maxiter = 1 in HF, SCF won't optimize orbitals.
