### ISSUE TITLE
Clean up finite difference code.

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#95]
All of the finite difference code needs clean up.

(1) Variables should not be declared at the beginning of the function! (we are not using Fortran!!)
(2) Scope should be used to make it readable (see hess.cc line 151).
(3) If not necessary, the function should not be modifying private member variables like ref_ or geom_.

finite.cc and also other functions such as FiniteNacm<CASPT2Energy>::compute().

**Comment by jwpk1201** [comment]
OK, I will work on it.

**Comment by jwpk1201** [comment]
The finite difference codes have been cleaned up. The redundancies in get_energy_ and construct_method should be resolved (thinking about it).

**Comment by shiozaki** [comment]
I'll keep this open till construct_method is cleaned up.

**Comment by shiozaki** [comment]
Fixed by 61ec299c258d082558a4443877f6faeb0620fc66
