### ISSUE TITLE
single state caspt2 is not working

### ISSUE THREAD

**Issue by jesusG-V** [nubakery/bagel#96]
After the new updates, the input:

{
 "title" : "casscf",
 "maxiter" : 200,
 "nact" : 10,
 "nclosed" : 26,
 "nstate" : 5

},

{
 "title" : "smith",
 "ms" : true,
 "xms" : false,
 "sssr" : true,
 "shift" : 0.2
}

is generating the  following error:

  ERROR: EXCEPTION RAISED:  caspt2 method is not implemented in SMITH

Looking the code (smith.cc), it should not happen, any idea?

**Comment by shiozaki** [comment]
You may need to do autoreconf and configure/compile again (we change the default to compile SMITH, so that change may have confused your build). Sorry for inconvenience.

We are making those changes to prepare for an official release late this month.

**Comment by jesusG-V** [comment]
Perfect, 

After recompiling it is working now, thanks a lot.
