### ISSUE TITLE
Minimal distance conical intersection search 

### ISSUE THREAD

**Issue by shiozaki** [nubakery/bagel#97]
to be implemented by the release.

**Comment by jwpk1201** [comment]
MDCI search is implemented. This is done by modifying the search gradient for MECI,
\mathbf{g} = \nabla (E_2 - E_1) + \mathbf{P} \nabla (E_2),
where the operator P projects out the interstate coupling and gradient difference, into
\mathbf{g} = \nabla (E_2 - E_1) + \mathbf{P} \nabla (d^2 / (d + 0.1))
where d is the Euclidean distance to the reference geometry. The factor of 0.1 is included as in JPCB 2008, 112, 405--413.

The convergence for MDCI using gradient projection is not very good (compared to MECI), and a good initial guess and the smaller step size might be needed to make it converge. The reference geometry is the first geometry of the optimization by default, but can be explicitly put into the program by setting

"mdci_reference_geometry" : true,
"refgeom" : {
  "basis" : "svp",
 ...
  "geometry" : [
  {"atom" : "C", "xyz" : [    -12.562212,      7.867455,      0.030316 ] },
  ...
  ]
}

**Comment by shiozaki** [comment]
I'll close this after this is merged into master. Also write a test case.

**Comment by shiozaki** [comment]
Jae Woo - don't forget to write a test case.
